"""
Sentinel NER — Disaster Chatbot Schemas
Defines request and response contracts for the Gemini-powered Disaster AI Copilot.
"""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class ChatMessage(BaseModel):
    role: str = Field(..., description="Message author role: 'user', 'model', or 'assistant'")
    content: str = Field(..., description="Text content of the message")
    timestamp: Optional[str] = Field(None, description="ISO timestamp of message")


class EmergencyContact(BaseModel):
    service: str = Field(..., description="Name of emergency response agency")
    number: str = Field(..., description="Contact phone or helpline number")
    description: str = Field(..., description="Jurisdiction or role of the agency")


class DisasterChatRequest(BaseModel):
    message: str = Field(..., description="User question or distress prompt about disasters")
    conversation_history: Optional[List[ChatMessage]] = Field(default_factory=list, description="Prior conversation context")
    state: Optional[str] = Field("Mizoram", description="Northeast India State context (e.g. Mizoram, Sikkim, Assam)")
    district: Optional[str] = Field(None, description="District or highway corridor context (e.g. Aizawl, NH-54, Gangtok)")
    gemini_api_key: Optional[str] = Field(None, description="Optional client-provided Google Gemini API key")


class DisasterChatResponse(BaseModel):
    model_config = {"protected_namespaces": ()}

    reply: str = Field(..., description="Comprehensive disaster intelligence or guidance response")
    model_used: str = Field(..., description="Identifier of the model or engine used (e.g. 'gemini-2.5-flash' or 'sentinel-disaster-kb-v1')")
    is_live_gemini: bool = Field(..., description="True if response was generated by live Google Gemini API")
    disaster_category: str = Field("General Hazard", description="Classified hazard type: Landslide, Flash Flood, Cloudburst, Earthquake, Structural Failure")
    severity_level: str = Field("ADVISORY", description="Severity level: ADVISORY, WATCH, WARNING, EMERGENCY")
    actionable_checklist: List[str] = Field(default_factory=list, description="Immediate step-by-step actions for life safety")
    emergency_contacts: List[EmergencyContact] = Field(default_factory=list, description="Relevant emergency helpline numbers")
    source_citations: List[str] = Field(default_factory=list, description="Authoritative sources (e.g. NDMA SOP, GSI Guidelines, IMD Bulletin)")


class DisasterTopic(BaseModel):
    id: str
    category: str
    title: str
    prompt: str
    icon_name: str


class DisasterTopicGroup(BaseModel):
    category: str
    topics: List[DisasterTopic]


class VerifyKeyRequest(BaseModel):
    gemini_api_key: str = Field(..., description="Google Gemini API key to test")


class VerifyKeyResponse(BaseModel):
    valid: bool
    model: Optional[str] = None
    message: str
