/**
 * Sentinel NER — Live Weather & 7-Day Forecasting Telemetry Dataset
 *
 * Comprehensive meteorological intelligence for all 8 states of Northeast India:
 * Mizoram, Sikkim, Assam, Meghalaya, Arunachal Pradesh, Nagaland, Manipur, Tripura.
 * Grounded in India Meteorological Department (IMD) RMC Guwahati, NCMRWF ensemble forecasts,
 * and NASA GPM IMERG real-time precipitation grids.
 */

export type WeatherConditionCode =
  | "rain_heavy"
  | "thunderstorm"
  | "rain_moderate"
  | "drizzle"
  | "overcast"
  | "partly_cloudy"
  | "clear";

export type WeatherAlertLevel = "RED" | "ORANGE" | "YELLOW" | "GREEN";

export type LandslideRiskTier = "CRITICAL" | "ELEVATED" | "MODERATE" | "LOW";

export const NE_STATES = [
  "All Northeast",
  "Mizoram",
  "Sikkim",
  "Assam",
  "Meghalaya",
  "Arunachal Pradesh",
  "Nagaland",
  "Manipur",
  "Tripura",
] as const;

export type NEState = (typeof NE_STATES)[number];

export interface HourlyForecastBlock {
  time: string; // "00:00", "04:00", "08:00", "12:00", "16:00", "20:00"
  tempC: number;
  rainRateMmH: number;
  rainChancePct: number;
  conditionCode: WeatherConditionCode;
}

export interface DailyForecast {
  dayOffset: number; // 1 (tomorrow) to 7
  dayName: string; // "Wed", "Thu", "Fri", etc.
  dateFormatted: string; // "09 Sep", "10 Sep", etc.
  condition: string;
  conditionCode: WeatherConditionCode;
  tempMaxC: number;
  tempMinC: number;
  precipitationChancePct: number;
  expectedRainfallMm: number;
  windSpeedMaxKmh: number;
  windDirection: string;
  humidityAvgPct: number;
  landslideRiskTier: LandslideRiskTier;
  landslideRiskSummary: string;
  hourlyPreview: HourlyForecastBlock[];
}

export interface LiveWeatherReport {
  tempC: number;
  feelsLikeC: number;
  condition: string;
  conditionCode: WeatherConditionCode;
  tempMaxTodayC: number;
  tempMinTodayC: number;
  humidityPct: number;
  windSpeedKmh: number;
  windDirection: string;
  windGustKmh: number;
  pressureHpa: number;
  dewPointC: number;
  uvIndex: number;
  visibilityKm: number;
  cloudCoverPct: number;
  precipitationRateMmH: number;
  rainAccumulated24hMm: number;
  rainAccumulated72hMm: number;
  aqi: number;
  aqiLabel: string;
  soilMoistureVwc: number; // Volumetric Water Content %
  alertLevel: WeatherAlertLevel;
  alertHeadline: string;
  alertDescription: string;
  dopplerRadarStatus: string;
  dopplerEchoDbz: number;
  stationStatus: "OPERATIONAL" | "STANDBY" | "MAINTENANCE";
  timestamp: string;
}

export interface WeatherStation {
  id: string;
  name: string;
  state: Exclude<NEState, "All Northeast">;
  district: string;
  corridor: string;
  highwayCode: string;
  elevationM: number;
  latitude: number;
  longitude: number;
  imdRadarStation: string;
  live: LiveWeatherReport;
  forecast7Day: DailyForecast[];
}

function getRelativeDate(daysFromNow: number): { dayName: string; dateFormatted: string } {
  const base = new Date(Date.now() + daysFromNow * 86400000);
  const dayName = base.toLocaleDateString("en-IN", { weekday: "short" });
  const dateFormatted = base.toLocaleDateString("en-IN", { day: "2-digit", month: "short" });
  return { dayName, dateFormatted };
}

export const WEATHER_STATIONS: WeatherStation[] = [
  // 1. MIZORAM (Aizawl & Lunglei)
  {
    id: "aizawl-nh54",
    name: "Aizawl Central & Durtlang Ridge",
    state: "Mizoram",
    district: "Aizawl",
    corridor: "NH-54 (Aizawl-Lunglei Lifeline)",
    highwayCode: "NH-54",
    elevationM: 1132,
    latitude: 23.7307,
    longitude: 92.7173,
    imdRadarStation: "IMD DWR Silchar / Aizawl Doppler Radar",
    live: {
      tempC: 22.4,
      feelsLikeC: 24.1,
      condition: "Heavy Monsoon Downpour",
      conditionCode: "rain_heavy",
      tempMaxTodayC: 25.0,
      tempMinTodayC: 20.8,
      humidityPct: 94,
      windSpeedKmh: 18,
      windDirection: "SSW",
      windGustKmh: 36,
      pressureHpa: 1008.2,
      dewPointC: 21.3,
      uvIndex: 2,
      visibilityKm: 2.5,
      cloudCoverPct: 98,
      precipitationRateMmH: 14.8,
      rainAccumulated24hMm: 114.5,
      rainAccumulated72hMm: 241.2,
      aqi: 24,
      aqiLabel: "Good",
      soilMoistureVwc: 82.4,
      alertLevel: "RED",
      alertHeadline: "Red Alert: Severe Rainfall & Active Slope Saturated",
      alertDescription:
        "Continuous precipitation exceeding 100mm threshold. High potential for rotational debris flows along Durtlang cut-slopes and NH-54 chainage 42-56.",
      dopplerRadarStatus: "Active Convective Band (48 dBZ Reflectivity)",
      dopplerEchoDbz: 48,
      stationStatus: "OPERATIONAL",
      timestamp: new Date().toISOString(),
    },
    forecast7Day: [
      {
        dayOffset: 1,
        ...getRelativeDate(1),
        condition: "Intense Thunderstorm & High Runoff",
        conditionCode: "thunderstorm",
        tempMaxC: 24.2,
        tempMinC: 20.1,
        precipitationChancePct: 95,
        expectedRainfallMm: 96.0,
        windSpeedMaxKmh: 42,
        windDirection: "SW",
        humidityAvgPct: 96,
        landslideRiskTier: "CRITICAL",
        landslideRiskSummary:
          "Next-day precipitation surge exceeds antecedent safety thresholds. Critical vigilance for NH-54 KM 42+350.",
        hourlyPreview: [
          { time: "00:00", tempC: 20.8, rainRateMmH: 12.0, rainChancePct: 90, conditionCode: "rain_heavy" },
          { time: "04:00", tempC: 20.2, rainRateMmH: 16.5, rainChancePct: 95, conditionCode: "thunderstorm" },
          { time: "08:00", tempC: 21.5, rainRateMmH: 22.0, rainChancePct: 98, conditionCode: "thunderstorm" },
          { time: "12:00", tempC: 23.8, rainRateMmH: 18.2, rainChancePct: 92, conditionCode: "rain_heavy" },
          { time: "16:00", tempC: 22.9, rainRateMmH: 14.0, rainChancePct: 88, conditionCode: "rain_moderate" },
          { time: "20:00", tempC: 21.4, rainRateMmH: 13.3, rainChancePct: 85, conditionCode: "rain_moderate" },
        ],
      },
      {
        dayOffset: 2,
        ...getRelativeDate(2),
        condition: "Continuous Heavy Showers",
        conditionCode: "rain_heavy",
        tempMaxC: 24.8,
        tempMinC: 20.5,
        precipitationChancePct: 90,
        expectedRainfallMm: 78.5,
        windSpeedMaxKmh: 34,
        windDirection: "SSW",
        humidityAvgPct: 92,
        landslideRiskTier: "CRITICAL",
        landslideRiskSummary: "Cumulative 5-day saturation reaches upper boundary. BRO emergency clearance teams on standby.",
        hourlyPreview: [
          { time: "00:00", tempC: 20.6, rainRateMmH: 10.5, rainChancePct: 85, conditionCode: "rain_moderate" },
          { time: "04:00", tempC: 20.4, rainRateMmH: 12.0, rainChancePct: 88, conditionCode: "rain_heavy" },
          { time: "08:00", tempC: 22.0, rainRateMmH: 15.0, rainChancePct: 90, conditionCode: "rain_heavy" },
          { time: "12:00", tempC: 24.5, rainRateMmH: 18.0, rainChancePct: 92, conditionCode: "rain_heavy" },
          { time: "16:00", tempC: 23.6, rainRateMmH: 13.0, rainChancePct: 85, conditionCode: "rain_moderate" },
          { time: "20:00", tempC: 21.8, rainRateMmH: 10.0, rainChancePct: 80, conditionCode: "rain_moderate" },
        ],
      },
      {
        dayOffset: 3,
        ...getRelativeDate(3),
        condition: "Moderate Rain with Isolated Heavy Spells",
        conditionCode: "rain_moderate",
        tempMaxC: 25.4,
        tempMinC: 21.0,
        precipitationChancePct: 80,
        expectedRainfallMm: 52.0,
        windSpeedMaxKmh: 28,
        windDirection: "S",
        humidityAvgPct: 88,
        landslideRiskTier: "ELEVATED",
        landslideRiskSummary: "Rainfall rate moderates slightly; subsurface drainage lag requires caution on steep cuts.",
        hourlyPreview: [
          { time: "00:00", tempC: 21.0, rainRateMmH: 7.2, rainChancePct: 75, conditionCode: "rain_moderate" },
          { time: "04:00", tempC: 20.8, rainRateMmH: 8.5, rainChancePct: 78, conditionCode: "rain_moderate" },
          { time: "08:00", tempC: 22.8, rainRateMmH: 11.0, rainChancePct: 82, conditionCode: "rain_moderate" },
          { time: "12:00", tempC: 25.1, rainRateMmH: 12.5, rainChancePct: 85, conditionCode: "rain_heavy" },
          { time: "16:00", tempC: 24.2, rainRateMmH: 7.8, rainChancePct: 75, conditionCode: "drizzle" },
          { time: "20:00", tempC: 22.0, rainRateMmH: 5.0, rainChancePct: 70, conditionCode: "drizzle" },
        ],
      },
      {
        dayOffset: 4,
        ...getRelativeDate(4),
        condition: "Scattered Showers & Overcast",
        conditionCode: "rain_moderate",
        tempMaxC: 26.0,
        tempMinC: 21.2,
        precipitationChancePct: 70,
        expectedRainfallMm: 38.0,
        windSpeedMaxKmh: 24,
        windDirection: "SSE",
        humidityAvgPct: 84,
        landslideRiskTier: "ELEVATED",
        landslideRiskSummary: "Surface runoff subsiding; subsoil pore pressure remains elevated.",
        hourlyPreview: [
          { time: "00:00", tempC: 21.2, rainRateMmH: 4.0, rainChancePct: 65, conditionCode: "drizzle" },
          { time: "04:00", tempC: 21.0, rainRateMmH: 5.2, rainChancePct: 68, conditionCode: "drizzle" },
          { time: "08:00", tempC: 23.2, rainRateMmH: 7.8, rainChancePct: 72, conditionCode: "rain_moderate" },
          { time: "12:00", tempC: 25.8, rainRateMmH: 9.0, rainChancePct: 75, conditionCode: "rain_moderate" },
          { time: "16:00", tempC: 24.9, rainRateMmH: 6.5, rainChancePct: 68, conditionCode: "drizzle" },
          { time: "20:00", tempC: 22.5, rainRateMmH: 5.5, rainChancePct: 62, conditionCode: "drizzle" },
        ],
      },
      {
        dayOffset: 5,
        ...getRelativeDate(5),
        condition: "Intermittent Rain & Ridge Fog",
        conditionCode: "drizzle",
        tempMaxC: 26.5,
        tempMinC: 21.5,
        precipitationChancePct: 60,
        expectedRainfallMm: 24.0,
        windSpeedMaxKmh: 20,
        windDirection: "SE",
        humidityAvgPct: 80,
        landslideRiskTier: "MODERATE",
        landslideRiskSummary: "Highway traffic nominal with caution on hairpin curves and rockfall catchment drains.",
        hourlyPreview: [
          { time: "00:00", tempC: 21.6, rainRateMmH: 2.5, rainChancePct: 50, conditionCode: "drizzle" },
          { time: "04:00", tempC: 21.4, rainRateMmH: 3.0, rainChancePct: 55, conditionCode: "drizzle" },
          { time: "08:00", tempC: 23.8, rainRateMmH: 4.5, rainChancePct: 60, conditionCode: "drizzle" },
          { time: "12:00", tempC: 26.2, rainRateMmH: 6.0, rainChancePct: 65, conditionCode: "rain_moderate" },
          { time: "16:00", tempC: 25.1, rainRateMmH: 4.0, rainChancePct: 58, conditionCode: "drizzle" },
          { time: "20:00", tempC: 23.0, rainRateMmH: 4.0, rainChancePct: 52, conditionCode: "overcast" },
        ],
      },
      {
        dayOffset: 6,
        ...getRelativeDate(6),
        condition: "Overcast with Passing Showers",
        conditionCode: "overcast",
        tempMaxC: 27.2,
        tempMinC: 22.0,
        precipitationChancePct: 45,
        expectedRainfallMm: 16.0,
        windSpeedMaxKmh: 18,
        windDirection: "SE",
        humidityAvgPct: 76,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Stable slope conditions prevailing. Monitoring returns to baseline status.",
        hourlyPreview: [
          { time: "00:00", tempC: 22.0, rainRateMmH: 1.5, rainChancePct: 40, conditionCode: "overcast" },
          { time: "04:00", tempC: 21.8, rainRateMmH: 1.8, rainChancePct: 42, conditionCode: "overcast" },
          { time: "08:00", tempC: 24.2, rainRateMmH: 3.0, rainChancePct: 48, conditionCode: "drizzle" },
          { time: "12:00", tempC: 27.0, rainRateMmH: 4.2, rainChancePct: 50, conditionCode: "drizzle" },
          { time: "16:00", tempC: 25.8, rainRateMmH: 3.0, rainChancePct: 44, conditionCode: "overcast" },
          { time: "20:00", tempC: 23.5, rainRateMmH: 2.5, rainChancePct: 38, conditionCode: "overcast" },
        ],
      },
      {
        dayOffset: 7,
        ...getRelativeDate(7),
        condition: "Partly Cloudy with Clearing Skies",
        conditionCode: "partly_cloudy",
        tempMaxC: 28.0,
        tempMinC: 22.4,
        precipitationChancePct: 35,
        expectedRainfallMm: 11.5,
        windSpeedMaxKmh: 16,
        windDirection: "E",
        humidityAvgPct: 72,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Corridor clear. Normal highway speeds and routine maintenance operations.",
        hourlyPreview: [
          { time: "00:00", tempC: 22.4, rainRateMmH: 0.8, rainChancePct: 30, conditionCode: "partly_cloudy" },
          { time: "04:00", tempC: 22.1, rainRateMmH: 1.0, rainChancePct: 32, conditionCode: "partly_cloudy" },
          { time: "08:00", tempC: 24.8, rainRateMmH: 2.0, rainChancePct: 36, conditionCode: "drizzle" },
          { time: "12:00", tempC: 27.8, rainRateMmH: 3.5, rainChancePct: 40, conditionCode: "drizzle" },
          { time: "16:00", tempC: 26.5, rainRateMmH: 2.2, rainChancePct: 35, conditionCode: "partly_cloudy" },
          { time: "20:00", tempC: 24.0, rainRateMmH: 2.0, rainChancePct: 28, conditionCode: "partly_cloudy" },
        ],
      },
    ],
  },
  {
    id: "lunglei-nh54",
    name: "Lunglei South & Hnahthial Approach",
    state: "Mizoram",
    district: "Lunglei",
    corridor: "NH-54 South Corridor",
    highwayCode: "NH-54",
    elevationM: 1022,
    latitude: 22.8878,
    longitude: 92.7397,
    imdRadarStation: "IMD DWR Silchar Radar",
    live: {
      tempC: 23.6,
      feelsLikeC: 25.2,
      condition: "Moderate Rain & Escarpment Mist",
      conditionCode: "rain_moderate",
      tempMaxTodayC: 26.2,
      tempMinTodayC: 21.0,
      humidityPct: 90,
      windSpeedKmh: 15,
      windDirection: "S",
      windGustKmh: 28,
      pressureHpa: 1010.5,
      dewPointC: 21.8,
      uvIndex: 3,
      visibilityKm: 4.0,
      cloudCoverPct: 90,
      precipitationRateMmH: 8.2,
      rainAccumulated24hMm: 68.4,
      rainAccumulated72hMm: 152.0,
      aqi: 20,
      aqiLabel: "Good",
      soilMoistureVwc: 74.6,
      alertLevel: "YELLOW",
      alertHeadline: "Yellow Alert: Moderate Rainfall with Localized Slump Risk",
      alertDescription: "Intermittent rainfall causing elevated soil saturation on steep valley flanks towards Tuipang.",
      dopplerRadarStatus: "Scattered Precipitation Cells (36 dBZ)",
      dopplerEchoDbz: 36,
      stationStatus: "OPERATIONAL",
      timestamp: new Date().toISOString(),
    },
    forecast7Day: [
      {
        dayOffset: 1,
        ...getRelativeDate(1),
        condition: "Heavy Rain & Hill Mist",
        conditionCode: "rain_heavy",
        tempMaxC: 25.0,
        tempMinC: 20.5,
        precipitationChancePct: 85,
        expectedRainfallMm: 62.0,
        windSpeedMaxKmh: 30,
        windDirection: "SSW",
        humidityAvgPct: 92,
        landslideRiskTier: "ELEVATED",
        landslideRiskSummary: "Moderate slope toe saturation. Regular patrols on south approach.",
        hourlyPreview: [
          { time: "00:00", tempC: 21.0, rainRateMmH: 6.0, rainChancePct: 75, conditionCode: "rain_moderate" },
          { time: "04:00", tempC: 20.8, rainRateMmH: 8.0, rainChancePct: 80, conditionCode: "rain_moderate" },
          { time: "08:00", tempC: 22.5, rainRateMmH: 12.0, rainChancePct: 88, conditionCode: "rain_heavy" },
          { time: "12:00", tempC: 24.8, rainRateMmH: 14.0, rainChancePct: 85, conditionCode: "rain_heavy" },
          { time: "16:00", tempC: 23.5, rainRateMmH: 8.5, rainChancePct: 78, conditionCode: "rain_moderate" },
          { time: "20:00", tempC: 22.0, rainRateMmH: 5.0, rainChancePct: 70, conditionCode: "drizzle" },
        ],
      },
      {
        dayOffset: 2,
        ...getRelativeDate(2),
        condition: "Moderate Showers",
        conditionCode: "rain_moderate",
        tempMaxC: 25.8,
        tempMinC: 21.0,
        precipitationChancePct: 75,
        expectedRainfallMm: 45.0,
        windSpeedMaxKmh: 24,
        windDirection: "S",
        humidityAvgPct: 88,
        landslideRiskTier: "ELEVATED",
        landslideRiskSummary: "Watch for minor cut-slope rock dislodgements.",
        hourlyPreview: [
          { time: "00:00", tempC: 21.2, rainRateMmH: 5.0, rainChancePct: 70, conditionCode: "drizzle" },
          { time: "04:00", tempC: 21.0, rainRateMmH: 6.5, rainChancePct: 75, conditionCode: "rain_moderate" },
          { time: "08:00", tempC: 23.0, rainRateMmH: 9.0, rainChancePct: 80, conditionCode: "rain_moderate" },
          { time: "12:00", tempC: 25.5, rainRateMmH: 10.0, rainChancePct: 80, conditionCode: "rain_moderate" },
          { time: "16:00", tempC: 24.2, rainRateMmH: 6.0, rainChancePct: 70, conditionCode: "drizzle" },
          { time: "20:00", tempC: 22.4, rainRateMmH: 4.0, rainChancePct: 65, conditionCode: "drizzle" },
        ],
      },
      {
        dayOffset: 3,
        ...getRelativeDate(3),
        condition: "Passing Rain",
        conditionCode: "drizzle",
        tempMaxC: 26.5,
        tempMinC: 21.5,
        precipitationChancePct: 65,
        expectedRainfallMm: 30.0,
        windSpeedMaxKmh: 20,
        windDirection: "SE",
        humidityAvgPct: 82,
        landslideRiskTier: "MODERATE",
        landslideRiskSummary: "Precipitation declining. Highway clear.",
        hourlyPreview: [
          { time: "00:00", tempC: 21.6, rainRateMmH: 3.0, rainChancePct: 60, conditionCode: "drizzle" },
          { time: "04:00", tempC: 21.2, rainRateMmH: 4.0, rainChancePct: 62, conditionCode: "drizzle" },
          { time: "08:00", tempC: 23.5, rainRateMmH: 5.5, rainChancePct: 65, conditionCode: "drizzle" },
          { time: "12:00", tempC: 26.0, rainRateMmH: 6.0, rainChancePct: 68, conditionCode: "rain_moderate" },
          { time: "16:00", tempC: 24.8, rainRateMmH: 4.0, rainChancePct: 60, conditionCode: "drizzle" },
          { time: "20:00", tempC: 23.0, rainRateMmH: 2.5, rainChancePct: 52, conditionCode: "overcast" },
        ],
      },
      {
        dayOffset: 4,
        ...getRelativeDate(4),
        condition: "Overcast",
        conditionCode: "overcast",
        tempMaxC: 27.0,
        tempMinC: 22.0,
        precipitationChancePct: 50,
        expectedRainfallMm: 18.0,
        windSpeedMaxKmh: 18,
        windDirection: "SE",
        humidityAvgPct: 78,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Nominal highway operations.",
        hourlyPreview: [
          { time: "00:00", tempC: 22.0, rainRateMmH: 2.0, rainChancePct: 45, conditionCode: "overcast" },
          { time: "04:00", tempC: 21.8, rainRateMmH: 2.2, rainChancePct: 48, conditionCode: "overcast" },
          { time: "08:00", tempC: 24.2, rainRateMmH: 3.5, rainChancePct: 52, conditionCode: "drizzle" },
          { time: "12:00", tempC: 26.8, rainRateMmH: 4.0, rainChancePct: 55, conditionCode: "drizzle" },
          { time: "16:00", tempC: 25.5, rainRateMmH: 2.8, rainChancePct: 48, conditionCode: "overcast" },
          { time: "20:00", tempC: 23.5, rainRateMmH: 2.0, rainChancePct: 40, conditionCode: "overcast" },
        ],
      },
      {
        dayOffset: 5,
        ...getRelativeDate(5),
        condition: "Scattered Sun & Cloud",
        conditionCode: "partly_cloudy",
        tempMaxC: 28.0,
        tempMinC: 22.5,
        precipitationChancePct: 40,
        expectedRainfallMm: 12.0,
        windSpeedMaxKmh: 16,
        windDirection: "E",
        humidityAvgPct: 74,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Clear road conditions.",
        hourlyPreview: [
          { time: "00:00", tempC: 22.5, rainRateMmH: 1.0, rainChancePct: 35, conditionCode: "partly_cloudy" },
          { time: "04:00", tempC: 22.2, rainRateMmH: 1.2, rainChancePct: 38, conditionCode: "partly_cloudy" },
          { time: "08:00", tempC: 25.0, rainRateMmH: 2.2, rainChancePct: 42, conditionCode: "drizzle" },
          { time: "12:00", tempC: 27.8, rainRateMmH: 3.0, rainChancePct: 45, conditionCode: "drizzle" },
          { time: "16:00", tempC: 26.2, rainRateMmH: 1.8, rainChancePct: 38, conditionCode: "partly_cloudy" },
          { time: "20:00", tempC: 24.0, rainRateMmH: 1.0, rainChancePct: 30, conditionCode: "partly_cloudy" },
        ],
      },
      {
        dayOffset: 6,
        ...getRelativeDate(6),
        condition: "Partly Cloudy",
        conditionCode: "partly_cloudy",
        tempMaxC: 28.5,
        tempMinC: 22.8,
        precipitationChancePct: 30,
        expectedRainfallMm: 8.0,
        windSpeedMaxKmh: 14,
        windDirection: "E",
        humidityAvgPct: 70,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Baseline nominal operations.",
        hourlyPreview: [
          { time: "00:00", tempC: 22.8, rainRateMmH: 0.5, rainChancePct: 25, conditionCode: "partly_cloudy" },
          { time: "04:00", tempC: 22.5, rainRateMmH: 0.8, rainChancePct: 28, conditionCode: "partly_cloudy" },
          { time: "08:00", tempC: 25.5, rainRateMmH: 1.5, rainChancePct: 32, conditionCode: "partly_cloudy" },
          { time: "12:00", tempC: 28.2, rainRateMmH: 2.0, rainChancePct: 35, conditionCode: "drizzle" },
          { time: "16:00", tempC: 26.8, rainRateMmH: 1.2, rainChancePct: 28, conditionCode: "partly_cloudy" },
          { time: "20:00", tempC: 24.5, rainRateMmH: 0.5, rainChancePct: 22, conditionCode: "clear" },
        ],
      },
      {
        dayOffset: 7,
        ...getRelativeDate(7),
        condition: "Clear Skies",
        conditionCode: "clear",
        tempMaxC: 29.0,
        tempMinC: 23.0,
        precipitationChancePct: 20,
        expectedRainfallMm: 4.0,
        windSpeedMaxKmh: 12,
        windDirection: "ENE",
        humidityAvgPct: 65,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Safe conditions for civil earthworks.",
        hourlyPreview: [
          { time: "00:00", tempC: 23.0, rainRateMmH: 0.2, rainChancePct: 15, conditionCode: "clear" },
          { time: "04:00", tempC: 22.8, rainRateMmH: 0.2, rainChancePct: 18, conditionCode: "clear" },
          { time: "08:00", tempC: 26.0, rainRateMmH: 0.5, rainChancePct: 20, conditionCode: "clear" },
          { time: "12:00", tempC: 28.8, rainRateMmH: 1.0, rainChancePct: 25, conditionCode: "partly_cloudy" },
          { time: "16:00", tempC: 27.2, rainRateMmH: 0.5, rainChancePct: 18, conditionCode: "clear" },
          { time: "20:00", tempC: 24.8, rainRateMmH: 0.2, rainChancePct: 15, conditionCode: "clear" },
        ],
      },
    ],
  },

  // 2. SIKKIM (Gangtok & Mangan)
  {
    id: "gangtok-nh10",
    name: "Gangtok & Teesta Chute",
    state: "Sikkim",
    district: "East Sikkim / Gangtok",
    corridor: "NH-10 (Siliguri-Gangtok Lifeline)",
    highwayCode: "NH-10",
    elevationM: 1650,
    latitude: 27.3389,
    longitude: 88.6065,
    imdRadarStation: "IMD DWR Bagdogra / Gangtok Radar",
    live: {
      tempC: 18.2,
      feelsLikeC: 19.5,
      condition: "Torrential Downpour & Ridge Fog",
      conditionCode: "rain_heavy",
      tempMaxTodayC: 21.0,
      tempMinTodayC: 16.5,
      humidityPct: 96,
      windSpeedKmh: 22,
      windDirection: "NW",
      windGustKmh: 45,
      pressureHpa: 985.4,
      dewPointC: 17.5,
      uvIndex: 1,
      visibilityKm: 1.2,
      cloudCoverPct: 100,
      precipitationRateMmH: 18.6,
      rainAccumulated24hMm: 142.8,
      rainAccumulated72hMm: 310.4,
      aqi: 18,
      aqiLabel: "Good",
      soilMoistureVwc: 88.1,
      alertLevel: "RED",
      alertHeadline: "Red Alert: Flash Floods & Teesta Valley Chute Failure Risk",
      alertDescription:
        "Debris flow risk critically elevated between 29th Mile and Bhalu Khola. Heavy rainfall upstream in Lachen-Lachung catchments.",
      dopplerRadarStatus: "Severe Convective Band (52 dBZ)",
      dopplerEchoDbz: 52,
      stationStatus: "OPERATIONAL",
      timestamp: new Date().toISOString(),
    },
    forecast7Day: [
      {
        dayOffset: 1,
        ...getRelativeDate(1),
        condition: "Severe Torrential Rain & Landslide Threat",
        conditionCode: "thunderstorm",
        tempMaxC: 20.0,
        tempMinC: 15.8,
        precipitationChancePct: 98,
        expectedRainfallMm: 115.0,
        windSpeedMaxKmh: 48,
        windDirection: "NW",
        humidityAvgPct: 98,
        landslideRiskTier: "CRITICAL",
        landslideRiskSummary: "Maximum risk for NH-10. High probability of road blockages at 29th Mile.",
        hourlyPreview: [
          { time: "00:00", tempC: 16.2, rainRateMmH: 15.0, rainChancePct: 95, conditionCode: "rain_heavy" },
          { time: "04:00", tempC: 15.8, rainRateMmH: 22.0, rainChancePct: 98, conditionCode: "thunderstorm" },
          { time: "08:00", tempC: 17.5, rainRateMmH: 28.5, rainChancePct: 99, conditionCode: "thunderstorm" },
          { time: "12:00", tempC: 19.8, rainRateMmH: 24.0, rainChancePct: 96, conditionCode: "rain_heavy" },
          { time: "16:00", tempC: 18.4, rainRateMmH: 16.0, rainChancePct: 92, conditionCode: "rain_heavy" },
          { time: "20:00", tempC: 17.0, rainRateMmH: 9.5, rainChancePct: 88, conditionCode: "rain_moderate" },
        ],
      },
      {
        dayOffset: 2,
        ...getRelativeDate(2),
        condition: "Heavy Rain with Thunderstorms",
        conditionCode: "rain_heavy",
        tempMaxC: 20.5,
        tempMinC: 16.2,
        precipitationChancePct: 92,
        expectedRainfallMm: 85.0,
        windSpeedMaxKmh: 36,
        windDirection: "WNW",
        humidityAvgPct: 94,
        landslideRiskTier: "CRITICAL",
        landslideRiskSummary: "Critical saturation persists. Teesta river scouring highway embankments.",
        hourlyPreview: [
          { time: "00:00", tempC: 16.4, rainRateMmH: 12.0, rainChancePct: 88, conditionCode: "rain_moderate" },
          { time: "04:00", tempC: 16.0, rainRateMmH: 14.5, rainChancePct: 90, conditionCode: "rain_heavy" },
          { time: "08:00", tempC: 18.0, rainRateMmH: 18.0, rainChancePct: 94, conditionCode: "rain_heavy" },
          { time: "12:00", tempC: 20.2, rainRateMmH: 20.5, rainChancePct: 95, conditionCode: "rain_heavy" },
          { time: "16:00", tempC: 19.0, rainRateMmH: 12.0, rainChancePct: 88, conditionCode: "rain_moderate" },
          { time: "20:00", tempC: 17.5, rainRateMmH: 8.0, rainChancePct: 82, conditionCode: "rain_moderate" },
        ],
      },
      {
        dayOffset: 3,
        ...getRelativeDate(3),
        condition: "Moderate to Heavy Showers",
        conditionCode: "rain_moderate",
        tempMaxC: 21.5,
        tempMinC: 16.8,
        precipitationChancePct: 82,
        expectedRainfallMm: 58.0,
        windSpeedMaxKmh: 28,
        windDirection: "W",
        humidityAvgPct: 90,
        landslideRiskTier: "ELEVATED",
        landslideRiskSummary: "Precipitation slowly decreases; slope regolith remains near liquid limit.",
        hourlyPreview: [
          { time: "00:00", tempC: 16.8, rainRateMmH: 8.0, rainChancePct: 78, conditionCode: "rain_moderate" },
          { time: "04:00", tempC: 16.5, rainRateMmH: 9.2, rainChancePct: 80, conditionCode: "rain_moderate" },
          { time: "08:00", tempC: 18.6, rainRateMmH: 12.5, rainChancePct: 85, conditionCode: "rain_moderate" },
          { time: "12:00", tempC: 21.2, rainRateMmH: 14.0, rainChancePct: 88, conditionCode: "rain_heavy" },
          { time: "16:00", tempC: 20.0, rainRateMmH: 8.5, rainChancePct: 80, conditionCode: "rain_moderate" },
          { time: "20:00", tempC: 18.0, rainRateMmH: 5.8, rainChancePct: 72, conditionCode: "drizzle" },
        ],
      },
      {
        dayOffset: 4,
        ...getRelativeDate(4),
        condition: "Passing Rain & Low Cloud",
        conditionCode: "drizzle",
        tempMaxC: 22.0,
        tempMinC: 17.0,
        precipitationChancePct: 65,
        expectedRainfallMm: 34.0,
        windSpeedMaxKmh: 22,
        windDirection: "SW",
        humidityAvgPct: 85,
        landslideRiskTier: "MODERATE",
        landslideRiskSummary: "Restoration crews cleared minor slumps. Controlled one-way traffic.",
        hourlyPreview: [
          { time: "00:00", tempC: 17.0, rainRateMmH: 4.5, rainChancePct: 62, conditionCode: "drizzle" },
          { time: "04:00", tempC: 16.8, rainRateMmH: 5.0, rainChancePct: 65, conditionCode: "drizzle" },
          { time: "08:00", tempC: 19.0, rainRateMmH: 7.0, rainChancePct: 68, conditionCode: "rain_moderate" },
          { time: "12:00", tempC: 21.8, rainRateMmH: 8.5, rainChancePct: 70, conditionCode: "rain_moderate" },
          { time: "16:00", tempC: 20.5, rainRateMmH: 5.2, rainChancePct: 64, conditionCode: "drizzle" },
          { time: "20:00", tempC: 18.5, rainRateMmH: 3.8, rainChancePct: 58, conditionCode: "drizzle" },
        ],
      },
      {
        dayOffset: 5,
        ...getRelativeDate(5),
        condition: "Scattered Rain & Mist",
        conditionCode: "drizzle",
        tempMaxC: 23.0,
        tempMinC: 17.5,
        precipitationChancePct: 55,
        expectedRainfallMm: 22.0,
        windSpeedMaxKmh: 18,
        windDirection: "S",
        humidityAvgPct: 80,
        landslideRiskTier: "MODERATE",
        landslideRiskSummary: "Pore water pressure stabilizing across primary cross-sections.",
        hourlyPreview: [
          { time: "00:00", tempC: 17.5, rainRateMmH: 2.8, rainChancePct: 50, conditionCode: "drizzle" },
          { time: "04:00", tempC: 17.2, rainRateMmH: 3.2, rainChancePct: 52, conditionCode: "drizzle" },
          { time: "08:00", tempC: 19.8, rainRateMmH: 4.8, rainChancePct: 58, conditionCode: "drizzle" },
          { time: "12:00", tempC: 22.6, rainRateMmH: 5.5, rainChancePct: 60, conditionCode: "drizzle" },
          { time: "16:00", tempC: 21.2, rainRateMmH: 3.5, rainChancePct: 54, conditionCode: "drizzle" },
          { time: "20:00", tempC: 19.0, rainRateMmH: 2.2, rainChancePct: 48, conditionCode: "overcast" },
        ],
      },
      {
        dayOffset: 6,
        ...getRelativeDate(6),
        condition: "Overcast with Isolated Showers",
        conditionCode: "overcast",
        tempMaxC: 24.0,
        tempMinC: 18.0,
        precipitationChancePct: 40,
        expectedRainfallMm: 14.0,
        windSpeedMaxKmh: 15,
        windDirection: "SSE",
        humidityAvgPct: 75,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Nominal operational status returning to corridor.",
        hourlyPreview: [
          { time: "00:00", tempC: 18.0, rainRateMmH: 1.5, rainChancePct: 35, conditionCode: "overcast" },
          { time: "04:00", tempC: 17.8, rainRateMmH: 1.8, rainChancePct: 38, conditionCode: "overcast" },
          { time: "08:00", tempC: 20.5, rainRateMmH: 2.8, rainChancePct: 42, conditionCode: "drizzle" },
          { time: "12:00", tempC: 23.6, rainRateMmH: 3.8, rainChancePct: 45, conditionCode: "drizzle" },
          { time: "16:00", tempC: 22.0, rainRateMmH: 2.5, rainChancePct: 40, conditionCode: "overcast" },
          { time: "20:00", tempC: 19.8, rainRateMmH: 1.6, rainChancePct: 32, conditionCode: "overcast" },
        ],
      },
      {
        dayOffset: 7,
        ...getRelativeDate(7),
        condition: "Partly Cloudy with Sunny Breaks",
        conditionCode: "partly_cloudy",
        tempMaxC: 25.0,
        tempMinC: 18.5,
        precipitationChancePct: 30,
        expectedRainfallMm: 8.5,
        windSpeedMaxKmh: 14,
        windDirection: "SE",
        humidityAvgPct: 70,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Green condition. Both lanes open.",
        hourlyPreview: [
          { time: "00:00", tempC: 18.5, rainRateMmH: 0.5, rainChancePct: 25, conditionCode: "partly_cloudy" },
          { time: "04:00", tempC: 18.2, rainRateMmH: 0.8, rainChancePct: 28, conditionCode: "partly_cloudy" },
          { time: "08:00", tempC: 21.2, rainRateMmH: 1.5, rainChancePct: 32, conditionCode: "partly_cloudy" },
          { time: "12:00", tempC: 24.8, rainRateMmH: 2.5, rainChancePct: 35, conditionCode: "drizzle" },
          { time: "16:00", tempC: 23.2, rainRateMmH: 1.8, rainChancePct: 30, conditionCode: "partly_cloudy" },
          { time: "20:00", tempC: 20.5, rainRateMmH: 0.9, rainChancePct: 22, conditionCode: "clear" },
        ],
      },
    ],
  },

  // 3. ASSAM (Dima Hasao & Guwahati)
  {
    id: "guwahati-nh27",
    name: "Dima Hasao & Jatinga Chute",
    state: "Assam",
    district: "Dima Hasao",
    corridor: "NH-27 East-West Corridor (Haflong-Silchar)",
    highwayCode: "NH-27",
    elevationM: 615,
    latitude: 25.1842,
    longitude: 93.0426,
    imdRadarStation: "IMD DWR Guwahati",
    live: {
      tempC: 27.8,
      feelsLikeC: 32.4,
      condition: "Tropical Thunderstorm & Mudflow Alert",
      conditionCode: "thunderstorm",
      tempMaxTodayC: 30.5,
      tempMinTodayC: 25.0,
      humidityPct: 91,
      windSpeedKmh: 24,
      windDirection: "S",
      windGustKmh: 52,
      pressureHpa: 1004.8,
      dewPointC: 26.1,
      uvIndex: 4,
      visibilityKm: 3.5,
      cloudCoverPct: 95,
      precipitationRateMmH: 24.2,
      rainAccumulated24hMm: 98.4,
      rainAccumulated72hMm: 215.0,
      aqi: 32,
      aqiLabel: "Good",
      soilMoistureVwc: 79.5,
      alertLevel: "ORANGE",
      alertHeadline: "Orange Alert: Jatinga Chute Mudflow & Rail Cutting Saturation",
      alertDescription:
        "Intense downpours triggered slope creep on shale slopes. NF Railway and NHIDCL heavy machinery staged at New Haflong.",
      dopplerRadarStatus: "Intense Convective Band (46 dBZ)",
      dopplerEchoDbz: 46,
      stationStatus: "OPERATIONAL",
      timestamp: new Date().toISOString(),
    },
    forecast7Day: [
      {
        dayOffset: 1,
        ...getRelativeDate(1),
        condition: "Severe Thunderstorm with Gusty Winds",
        conditionCode: "thunderstorm",
        tempMaxC: 29.5,
        tempMinC: 24.5,
        precipitationChancePct: 92,
        expectedRainfallMm: 88.0,
        windSpeedMaxKmh: 54,
        windDirection: "S",
        humidityAvgPct: 92,
        landslideRiskTier: "CRITICAL",
        landslideRiskSummary: "Flash runoff in steep gullies. High probability of road and rail disruptions.",
        hourlyPreview: [
          { time: "00:00", tempC: 25.0, rainRateMmH: 14.0, rainChancePct: 88, conditionCode: "rain_heavy" },
          { time: "04:00", tempC: 24.5, rainRateMmH: 18.5, rainChancePct: 92, conditionCode: "thunderstorm" },
          { time: "08:00", tempC: 26.8, rainRateMmH: 24.0, rainChancePct: 95, conditionCode: "thunderstorm" },
          { time: "12:00", tempC: 29.2, rainRateMmH: 16.0, rainChancePct: 90, conditionCode: "rain_heavy" },
          { time: "16:00", tempC: 28.0, rainRateMmH: 10.5, rainChancePct: 84, conditionCode: "rain_moderate" },
          { time: "20:00", tempC: 26.2, rainRateMmH: 5.0, rainChancePct: 78, conditionCode: "rain_moderate" },
        ],
      },
      {
        dayOffset: 2,
        ...getRelativeDate(2),
        condition: "Frequent Heavy Showers",
        conditionCode: "rain_heavy",
        tempMaxC: 30.0,
        tempMinC: 25.0,
        precipitationChancePct: 85,
        expectedRainfallMm: 64.0,
        windSpeedMaxKmh: 38,
        windDirection: "SSW",
        humidityAvgPct: 88,
        landslideRiskTier: "ELEVATED",
        landslideRiskSummary: "Active monitoring of railway cuttings along Lumding-Badarpur hill section.",
        hourlyPreview: [
          { time: "00:00", tempC: 25.2, rainRateMmH: 8.0, rainChancePct: 80, conditionCode: "rain_moderate" },
          { time: "04:00", tempC: 24.8, rainRateMmH: 10.5, rainChancePct: 84, conditionCode: "rain_heavy" },
          { time: "08:00", tempC: 27.5, rainRateMmH: 15.0, rainChancePct: 88, conditionCode: "rain_heavy" },
          { time: "12:00", tempC: 29.8, rainRateMmH: 16.5, rainChancePct: 88, conditionCode: "rain_heavy" },
          { time: "16:00", tempC: 28.5, rainRateMmH: 9.0, rainChancePct: 80, conditionCode: "rain_moderate" },
          { time: "20:00", tempC: 26.8, rainRateMmH: 5.0, rainChancePct: 74, conditionCode: "rain_moderate" },
        ],
      },
      {
        dayOffset: 3,
        ...getRelativeDate(3),
        condition: "Moderate Rain with Sunny Intervals",
        conditionCode: "rain_moderate",
        tempMaxC: 31.2,
        tempMinC: 25.4,
        precipitationChancePct: 75,
        expectedRainfallMm: 42.0,
        windSpeedMaxKmh: 30,
        windDirection: "SW",
        humidityAvgPct: 82,
        landslideRiskTier: "ELEVATED",
        landslideRiskSummary: "Intermittent runoff. Heavy vehicles warned against excessive speed on wet bends.",
        hourlyPreview: [
          { time: "00:00", tempC: 25.4, rainRateMmH: 5.0, rainChancePct: 70, conditionCode: "rain_moderate" },
          { time: "04:00", tempC: 25.0, rainRateMmH: 6.5, rainChancePct: 72, conditionCode: "rain_moderate" },
          { time: "08:00", tempC: 28.0, rainRateMmH: 9.0, rainChancePct: 78, conditionCode: "rain_moderate" },
          { time: "12:00", tempC: 31.0, rainRateMmH: 11.5, rainChancePct: 80, conditionCode: "rain_moderate" },
          { time: "16:00", tempC: 29.5, rainRateMmH: 6.2, rainChancePct: 72, conditionCode: "drizzle" },
          { time: "20:00", tempC: 27.2, rainRateMmH: 3.8, rainChancePct: 65, conditionCode: "drizzle" },
        ],
      },
      {
        dayOffset: 4,
        ...getRelativeDate(4),
        condition: "Scattered Rain Showers",
        conditionCode: "rain_moderate",
        tempMaxC: 32.0,
        tempMinC: 26.0,
        precipitationChancePct: 62,
        expectedRainfallMm: 28.0,
        windSpeedMaxKmh: 24,
        windDirection: "S",
        humidityAvgPct: 78,
        landslideRiskTier: "MODERATE",
        landslideRiskSummary: "Runoff settling into valley channels. Maintenance crews clearing catch-pits.",
        hourlyPreview: [
          { time: "00:00", tempC: 26.0, rainRateMmH: 3.0, rainChancePct: 58, conditionCode: "drizzle" },
          { time: "04:00", tempC: 25.6, rainRateMmH: 3.8, rainChancePct: 60, conditionCode: "drizzle" },
          { time: "08:00", tempC: 28.8, rainRateMmH: 6.0, rainChancePct: 65, conditionCode: "rain_moderate" },
          { time: "12:00", tempC: 31.8, rainRateMmH: 7.5, rainChancePct: 68, conditionCode: "rain_moderate" },
          { time: "16:00", tempC: 30.2, rainRateMmH: 4.5, rainChancePct: 60, conditionCode: "drizzle" },
          { time: "20:00", tempC: 28.0, rainRateMmH: 3.2, rainChancePct: 52, conditionCode: "drizzle" },
        ],
      },
      {
        dayOffset: 5,
        ...getRelativeDate(5),
        condition: "Partly Cloudy with Drizzle",
        conditionCode: "drizzle",
        tempMaxC: 32.8,
        tempMinC: 26.2,
        precipitationChancePct: 50,
        expectedRainfallMm: 18.0,
        windSpeedMaxKmh: 20,
        windDirection: "SE",
        humidityAvgPct: 74,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Drying cycle commencing across road cut slopes.",
        hourlyPreview: [
          { time: "00:00", tempC: 26.2, rainRateMmH: 2.0, rainChancePct: 45, conditionCode: "drizzle" },
          { time: "04:00", tempC: 25.8, rainRateMmH: 2.2, rainChancePct: 48, conditionCode: "drizzle" },
          { time: "08:00", tempC: 29.4, rainRateMmH: 3.8, rainChancePct: 52, conditionCode: "drizzle" },
          { time: "12:00", tempC: 32.5, rainRateMmH: 4.8, rainChancePct: 55, conditionCode: "drizzle" },
          { time: "16:00", tempC: 31.0, rainRateMmH: 3.0, rainChancePct: 48, conditionCode: "drizzle" },
          { time: "20:00", tempC: 28.5, rainRateMmH: 2.2, rainChancePct: 40, conditionCode: "overcast" },
        ],
      },
      {
        dayOffset: 6,
        ...getRelativeDate(6),
        condition: "Warm and Partly Cloudy",
        conditionCode: "partly_cloudy",
        tempMaxC: 33.5,
        tempMinC: 26.8,
        precipitationChancePct: 35,
        expectedRainfallMm: 10.0,
        windSpeedMaxKmh: 16,
        windDirection: "E",
        humidityAvgPct: 68,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Nominal operational state. Highway fully clear.",
        hourlyPreview: [
          { time: "00:00", tempC: 26.8, rainRateMmH: 1.0, rainChancePct: 30, conditionCode: "partly_cloudy" },
          { time: "04:00", tempC: 26.4, rainRateMmH: 1.2, rainChancePct: 32, conditionCode: "partly_cloudy" },
          { time: "08:00", tempC: 30.2, rainRateMmH: 2.0, rainChancePct: 38, conditionCode: "partly_cloudy" },
          { time: "12:00", tempC: 33.2, rainRateMmH: 3.0, rainChancePct: 40, conditionCode: "drizzle" },
          { time: "16:00", tempC: 31.8, rainRateMmH: 1.8, rainChancePct: 34, conditionCode: "partly_cloudy" },
          { time: "20:00", tempC: 29.0, rainRateMmH: 1.2, rainChancePct: 26, conditionCode: "clear" },
        ],
      },
      {
        dayOffset: 7,
        ...getRelativeDate(7),
        condition: "Clear and Humid",
        conditionCode: "clear",
        tempMaxC: 34.0,
        tempMinC: 27.0,
        precipitationChancePct: 25,
        expectedRainfallMm: 5.0,
        windSpeedMaxKmh: 14,
        windDirection: "E",
        humidityAvgPct: 64,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Safe operational window for transport and slope works.",
        hourlyPreview: [
          { time: "00:00", tempC: 27.0, rainRateMmH: 0.2, rainChancePct: 20, conditionCode: "clear" },
          { time: "04:00", tempC: 26.6, rainRateMmH: 0.5, rainChancePct: 22, conditionCode: "clear" },
          { time: "08:00", tempC: 30.8, rainRateMmH: 1.0, rainChancePct: 28, conditionCode: "partly_cloudy" },
          { time: "12:00", tempC: 33.8, rainRateMmH: 1.5, rainChancePct: 30, conditionCode: "partly_cloudy" },
          { time: "16:00", tempC: 32.2, rainRateMmH: 0.8, rainChancePct: 24, conditionCode: "clear" },
          { time: "20:00", tempC: 29.5, rainRateMmH: 0.5, rainChancePct: 18, conditionCode: "clear" },
        ],
      },
    ],
  },

  // 4. MEGHALAYA (Shillong & Sonapur Tunnel)
  {
    id: "shillong-nh6",
    name: "Shillong & Sonapur Tunnel",
    state: "Meghalaya",
    district: "East Jaintia Hills / Shillong",
    corridor: "NH-6 (Guwahati-Shillong-Silchar)",
    highwayCode: "NH-6",
    elevationM: 1496,
    latitude: 25.5788,
    longitude: 91.8933,
    imdRadarStation: "IMD DWR Sohra (Cherrapunji)",
    live: {
      tempC: 19.5,
      feelsLikeC: 20.8,
      condition: "Dense Orographic Rain & Escarpment Fog",
      conditionCode: "rain_heavy",
      tempMaxTodayC: 22.0,
      tempMinTodayC: 17.2,
      humidityPct: 98,
      windSpeedKmh: 26,
      windDirection: "SSW",
      windGustKmh: 48,
      pressureHpa: 994.0,
      dewPointC: 19.1,
      uvIndex: 2,
      visibilityKm: 0.8,
      cloudCoverPct: 100,
      precipitationRateMmH: 21.4,
      rainAccumulated24hMm: 165.2,
      rainAccumulated72hMm: 385.0,
      aqi: 14,
      aqiLabel: "Good",
      soilMoistureVwc: 91.2,
      alertLevel: "RED",
      alertHeadline: "Red Alert: Sonapur Rockfall Tunnel Detachment Risk",
      alertDescription:
        "Exceptional orographic enhancement across Meghalaya southern escarpment. Sonapur mud-chute actively discharging onto NH-6 apron.",
      dopplerRadarStatus: "Extreme Orographic Cloud Mass (50 dBZ)",
      dopplerEchoDbz: 50,
      stationStatus: "OPERATIONAL",
      timestamp: new Date().toISOString(),
    },
    forecast7Day: [
      {
        dayOffset: 1,
        ...getRelativeDate(1),
        condition: "Violent Orographic Downpour",
        conditionCode: "thunderstorm",
        tempMaxC: 21.0,
        tempMinC: 16.5,
        precipitationChancePct: 99,
        expectedRainfallMm: 135.0,
        windSpeedMaxKmh: 56,
        windDirection: "SSW",
        humidityAvgPct: 99,
        landslideRiskTier: "CRITICAL",
        landslideRiskSummary: "Maximum warning for Sonapur Tunnel approaches. Heavy machinery pre-positioned by BRO.",
        hourlyPreview: [
          { time: "00:00", tempC: 17.0, rainRateMmH: 18.0, rainChancePct: 98, conditionCode: "rain_heavy" },
          { time: "04:00", tempC: 16.5, rainRateMmH: 26.0, rainChancePct: 99, conditionCode: "thunderstorm" },
          { time: "08:00", tempC: 18.2, rainRateMmH: 32.0, rainChancePct: 100, conditionCode: "thunderstorm" },
          { time: "12:00", tempC: 20.8, rainRateMmH: 28.0, rainChancePct: 98, conditionCode: "rain_heavy" },
          { time: "16:00", tempC: 19.5, rainRateMmH: 18.5, rainChancePct: 95, conditionCode: "rain_heavy" },
          { time: "20:00", tempC: 17.8, rainRateMmH: 12.5, rainChancePct: 90, conditionCode: "rain_moderate" },
        ],
      },
      {
        dayOffset: 2,
        ...getRelativeDate(2),
        condition: "Continuous Heavy Torrential Rain",
        conditionCode: "rain_heavy",
        tempMaxC: 21.5,
        tempMinC: 17.0,
        precipitationChancePct: 95,
        expectedRainfallMm: 98.0,
        windSpeedMaxKmh: 44,
        windDirection: "S",
        humidityAvgPct: 96,
        landslideRiskTier: "CRITICAL",
        landslideRiskSummary: "Rockfall nets inspected. Heavy debris removal in progress on NH-6 bypass.",
        hourlyPreview: [
          { time: "00:00", tempC: 17.2, rainRateMmH: 14.0, rainChancePct: 92, conditionCode: "rain_heavy" },
          { time: "04:00", tempC: 16.8, rainRateMmH: 18.0, rainChancePct: 95, conditionCode: "rain_heavy" },
          { time: "08:00", tempC: 19.0, rainRateMmH: 22.0, rainChancePct: 96, conditionCode: "rain_heavy" },
          { time: "12:00", tempC: 21.2, rainRateMmH: 24.5, rainChancePct: 95, conditionCode: "rain_heavy" },
          { time: "16:00", tempC: 20.0, rainRateMmH: 14.0, rainChancePct: 90, conditionCode: "rain_moderate" },
          { time: "20:00", tempC: 18.2, rainRateMmH: 10.0, rainChancePct: 85, conditionCode: "rain_moderate" },
        ],
      },
      {
        dayOffset: 3,
        ...getRelativeDate(3),
        condition: "Heavy Showers with Thick Mist",
        conditionCode: "rain_moderate",
        tempMaxC: 22.5,
        tempMinC: 17.4,
        precipitationChancePct: 85,
        expectedRainfallMm: 68.0,
        windSpeedMaxKmh: 34,
        windDirection: "S",
        humidityAvgPct: 92,
        landslideRiskTier: "ELEVATED",
        landslideRiskSummary: "Rainfall easing from peak. Highway monitoring maintained round-the-clock.",
        hourlyPreview: [
          { time: "00:00", tempC: 17.5, rainRateMmH: 9.0, rainChancePct: 82, conditionCode: "rain_moderate" },
          { time: "04:00", tempC: 17.2, rainRateMmH: 11.0, rainChancePct: 85, conditionCode: "rain_moderate" },
          { time: "08:00", tempC: 19.8, rainRateMmH: 15.0, rainChancePct: 88, conditionCode: "rain_heavy" },
          { time: "12:00", tempC: 22.2, rainRateMmH: 16.5, rainChancePct: 88, conditionCode: "rain_heavy" },
          { time: "16:00", tempC: 21.0, rainRateMmH: 10.2, rainChancePct: 82, conditionCode: "rain_moderate" },
          { time: "20:00", tempC: 18.8, rainRateMmH: 6.3, rainChancePct: 75, conditionCode: "drizzle" },
        ],
      },
      {
        dayOffset: 4,
        ...getRelativeDate(4),
        condition: "Moderate Rain & Low Cloud",
        conditionCode: "rain_moderate",
        tempMaxC: 23.2,
        tempMinC: 17.8,
        precipitationChancePct: 72,
        expectedRainfallMm: 44.0,
        windSpeedMaxKmh: 26,
        windDirection: "SSE",
        humidityAvgPct: 86,
        landslideRiskTier: "ELEVATED",
        landslideRiskSummary: "Residual boulder dislodgements possible on steep sandstone cliffs.",
        hourlyPreview: [
          { time: "00:00", tempC: 18.0, rainRateMmH: 5.5, rainChancePct: 70, conditionCode: "drizzle" },
          { time: "04:00", tempC: 17.6, rainRateMmH: 6.8, rainChancePct: 72, conditionCode: "rain_moderate" },
          { time: "08:00", tempC: 20.4, rainRateMmH: 9.5, rainChancePct: 76, conditionCode: "rain_moderate" },
          { time: "12:00", tempC: 23.0, rainRateMmH: 11.0, rainChancePct: 78, conditionCode: "rain_moderate" },
          { time: "16:00", tempC: 21.8, rainRateMmH: 7.2, rainChancePct: 72, conditionCode: "drizzle" },
          { time: "20:00", tempC: 19.5, rainRateMmH: 4.0, rainChancePct: 65, conditionCode: "drizzle" },
        ],
      },
      {
        dayOffset: 5,
        ...getRelativeDate(5),
        condition: "Intermittent Rain Showers",
        conditionCode: "drizzle",
        tempMaxC: 24.0,
        tempMinC: 18.2,
        precipitationChancePct: 60,
        expectedRainfallMm: 28.0,
        windSpeedMaxKmh: 20,
        windDirection: "SE",
        humidityAvgPct: 82,
        landslideRiskTier: "MODERATE",
        landslideRiskSummary: "Highway speed restrictions relaxed during daylight hours.",
        hourlyPreview: [
          { time: "00:00", tempC: 18.2, rainRateMmH: 3.5, rainChancePct: 58, conditionCode: "drizzle" },
          { time: "04:00", tempC: 18.0, rainRateMmH: 4.0, rainChancePct: 60, conditionCode: "drizzle" },
          { time: "08:00", tempC: 21.0, rainRateMmH: 6.0, rainChancePct: 64, conditionCode: "drizzle" },
          { time: "12:00", tempC: 23.8, rainRateMmH: 7.0, rainChancePct: 65, conditionCode: "rain_moderate" },
          { time: "16:00", tempC: 22.5, rainRateMmH: 4.5, rainChancePct: 58, conditionCode: "drizzle" },
          { time: "20:00", tempC: 20.0, rainRateMmH: 3.0, rainChancePct: 50, conditionCode: "overcast" },
        ],
      },
      {
        dayOffset: 6,
        ...getRelativeDate(6),
        condition: "Overcast with Mountain Drizzle",
        conditionCode: "overcast",
        tempMaxC: 24.8,
        tempMinC: 18.6,
        precipitationChancePct: 45,
        expectedRainfallMm: 18.0,
        windSpeedMaxKmh: 16,
        windDirection: "E",
        humidityAvgPct: 78,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Drainage networks functioning normally.",
        hourlyPreview: [
          { time: "00:00", tempC: 18.6, rainRateMmH: 2.0, rainChancePct: 42, conditionCode: "overcast" },
          { time: "04:00", tempC: 18.4, rainRateMmH: 2.2, rainChancePct: 44, conditionCode: "overcast" },
          { time: "08:00", tempC: 21.6, rainRateMmH: 3.8, rainChancePct: 48, conditionCode: "drizzle" },
          { time: "12:00", tempC: 24.5, rainRateMmH: 4.5, rainChancePct: 50, conditionCode: "drizzle" },
          { time: "16:00", tempC: 23.0, rainRateMmH: 3.0, rainChancePct: 44, conditionCode: "overcast" },
          { time: "20:00", tempC: 20.8, rainRateMmH: 2.5, rainChancePct: 36, conditionCode: "overcast" },
        ],
      },
      {
        dayOffset: 7,
        ...getRelativeDate(7),
        condition: "Partly Cloudy with Clearing Skies",
        conditionCode: "partly_cloudy",
        tempMaxC: 25.5,
        tempMinC: 19.0,
        precipitationChancePct: 30,
        expectedRainfallMm: 10.0,
        windSpeedMaxKmh: 14,
        windDirection: "E",
        humidityAvgPct: 72,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "All routes operational. Clear conditions.",
        hourlyPreview: [
          { time: "00:00", tempC: 19.0, rainRateMmH: 0.8, rainChancePct: 28, conditionCode: "partly_cloudy" },
          { time: "04:00", tempC: 18.8, rainRateMmH: 1.0, rainChancePct: 30, conditionCode: "partly_cloudy" },
          { time: "08:00", tempC: 22.2, rainRateMmH: 2.0, rainChancePct: 34, conditionCode: "partly_cloudy" },
          { time: "12:00", tempC: 25.2, rainRateMmH: 2.8, rainChancePct: 35, conditionCode: "drizzle" },
          { time: "16:00", tempC: 23.8, rainRateMmH: 1.8, rainChancePct: 30, conditionCode: "partly_cloudy" },
          { time: "20:00", tempC: 21.2, rainRateMmH: 1.0, rainChancePct: 22, conditionCode: "clear" },
        ],
      },
    ],
  },

  // 5. ARUNACHAL PRADESH (Itanagar & Bhalukpong)
  {
    id: "itanagar-nh13",
    name: "Itanagar & Papum Pare Corridor",
    state: "Arunachal Pradesh",
    district: "Papum Pare",
    corridor: "NH-13 (Trans-Arunachal Highway)",
    highwayCode: "NH-13",
    elevationM: 750,
    latitude: 27.0844,
    longitude: 93.6053,
    imdRadarStation: "IMD DWR Mohanbari (Dibrugarh)",
    live: {
      tempC: 25.2,
      feelsLikeC: 28.0,
      condition: "Subtropical Downpour & Foothill Runoff",
      conditionCode: "rain_heavy",
      tempMaxTodayC: 28.0,
      tempMinTodayC: 22.4,
      humidityPct: 92,
      windSpeedKmh: 16,
      windDirection: "NE",
      windGustKmh: 38,
      pressureHpa: 1006.0,
      dewPointC: 23.5,
      uvIndex: 3,
      visibilityKm: 3.0,
      cloudCoverPct: 96,
      precipitationRateMmH: 16.2,
      rainAccumulated24hMm: 108.0,
      rainAccumulated72hMm: 230.0,
      aqi: 22,
      aqiLabel: "Good",
      soilMoistureVwc: 80.5,
      alertLevel: "ORANGE",
      alertHeadline: "Orange Alert: Trans-Arunachal Highway Escarpment Instability",
      alertDescription: "Heavy precipitation in foothill belts triggering debris slides between Hollongi and Itanagar.",
      dopplerRadarStatus: "Active Foothill Convective Cell (44 dBZ)",
      dopplerEchoDbz: 44,
      stationStatus: "OPERATIONAL",
      timestamp: new Date().toISOString(),
    },
    forecast7Day: [
      {
        dayOffset: 1,
        ...getRelativeDate(1),
        condition: "Heavy Rain with Mountain Thunderstorms",
        conditionCode: "thunderstorm",
        tempMaxC: 27.0,
        tempMinC: 22.0,
        precipitationChancePct: 90,
        expectedRainfallMm: 85.0,
        windSpeedMaxKmh: 40,
        windDirection: "NE",
        humidityAvgPct: 94,
        landslideRiskTier: "CRITICAL",
        landslideRiskSummary: "Toe erosion along Dikrong River basin. Pre-emptive monitoring on NH-13.",
        hourlyPreview: [
          { time: "00:00", tempC: 22.5, rainRateMmH: 11.0, rainChancePct: 85, conditionCode: "rain_heavy" },
          { time: "04:00", tempC: 22.0, rainRateMmH: 15.0, rainChancePct: 90, conditionCode: "thunderstorm" },
          { time: "08:00", tempC: 24.5, rainRateMmH: 20.0, rainChancePct: 92, conditionCode: "thunderstorm" },
          { time: "12:00", tempC: 26.8, rainRateMmH: 14.5, rainChancePct: 88, conditionCode: "rain_heavy" },
          { time: "16:00", tempC: 25.5, rainRateMmH: 9.0, rainChancePct: 80, conditionCode: "rain_moderate" },
          { time: "20:00", tempC: 23.8, rainRateMmH: 6.0, rainChancePct: 75, conditionCode: "rain_moderate" },
        ],
      },
      {
        dayOffset: 2,
        ...getRelativeDate(2),
        condition: "Continuous Rain Showers",
        conditionCode: "rain_heavy",
        tempMaxC: 27.5,
        tempMinC: 22.2,
        precipitationChancePct: 85,
        expectedRainfallMm: 68.0,
        windSpeedMaxKmh: 32,
        windDirection: "ENE",
        humidityAvgPct: 90,
        landslideRiskTier: "ELEVATED",
        landslideRiskSummary: "Watch for gravel slip-outs on steep embankments.",
        hourlyPreview: [
          { time: "00:00", tempC: 22.5, rainRateMmH: 8.0, rainChancePct: 80, conditionCode: "rain_moderate" },
          { time: "04:00", tempC: 22.0, rainRateMmH: 10.0, rainChancePct: 82, conditionCode: "rain_heavy" },
          { time: "08:00", tempC: 24.8, rainRateMmH: 14.0, rainChancePct: 86, conditionCode: "rain_heavy" },
          { time: "12:00", tempC: 27.0, rainRateMmH: 15.0, rainChancePct: 85, conditionCode: "rain_heavy" },
          { time: "16:00", tempC: 25.8, rainRateMmH: 8.5, rainChancePct: 78, conditionCode: "rain_moderate" },
          { time: "20:00", tempC: 24.0, rainRateMmH: 5.0, rainChancePct: 70, conditionCode: "rain_moderate" },
        ],
      },
      {
        dayOffset: 3,
        ...getRelativeDate(3),
        condition: "Moderate Rain",
        conditionCode: "rain_moderate",
        tempMaxC: 28.5,
        tempMinC: 22.8,
        precipitationChancePct: 75,
        expectedRainfallMm: 42.0,
        windSpeedMaxKmh: 24,
        windDirection: "E",
        humidityAvgPct: 84,
        landslideRiskTier: "ELEVATED",
        landslideRiskSummary: "Controlled convoy movement on high-elevation cuts.",
        hourlyPreview: [
          { time: "00:00", tempC: 23.0, rainRateMmH: 5.0, rainChancePct: 70, conditionCode: "rain_moderate" },
          { time: "04:00", tempC: 22.8, rainRateMmH: 6.0, rainChancePct: 72, conditionCode: "rain_moderate" },
          { time: "08:00", tempC: 25.5, rainRateMmH: 8.5, rainChancePct: 76, conditionCode: "rain_moderate" },
          { time: "12:00", tempC: 28.0, rainRateMmH: 9.5, rainChancePct: 78, conditionCode: "rain_moderate" },
          { time: "16:00", tempC: 26.5, rainRateMmH: 5.5, rainChancePct: 70, conditionCode: "drizzle" },
          { time: "20:00", tempC: 24.5, rainRateMmH: 3.5, rainChancePct: 62, conditionCode: "drizzle" },
        ],
      },
      {
        dayOffset: 4,
        ...getRelativeDate(4),
        condition: "Drizzle & Overcast",
        conditionCode: "drizzle",
        tempMaxC: 29.0,
        tempMinC: 23.0,
        precipitationChancePct: 60,
        expectedRainfallMm: 25.0,
        windSpeedMaxKmh: 20,
        windDirection: "E",
        humidityAvgPct: 80,
        landslideRiskTier: "MODERATE",
        landslideRiskSummary: "Highway surface damp but stable.",
        hourlyPreview: [
          { time: "00:00", tempC: 23.2, rainRateMmH: 2.8, rainChancePct: 55, conditionCode: "drizzle" },
          { time: "04:00", tempC: 23.0, rainRateMmH: 3.2, rainChancePct: 58, conditionCode: "drizzle" },
          { time: "08:00", tempC: 26.0, rainRateMmH: 4.8, rainChancePct: 62, conditionCode: "drizzle" },
          { time: "12:00", tempC: 28.8, rainRateMmH: 5.5, rainChancePct: 65, conditionCode: "drizzle" },
          { time: "16:00", tempC: 27.2, rainRateMmH: 3.5, rainChancePct: 58, conditionCode: "drizzle" },
          { time: "20:00", tempC: 25.0, rainRateMmH: 2.5, rainChancePct: 50, conditionCode: "overcast" },
        ],
      },
      {
        dayOffset: 5,
        ...getRelativeDate(5),
        condition: "Scattered Clouds with Sun",
        conditionCode: "partly_cloudy",
        tempMaxC: 30.0,
        tempMinC: 23.5,
        precipitationChancePct: 45,
        expectedRainfallMm: 15.0,
        windSpeedMaxKmh: 16,
        windDirection: "ESE",
        humidityAvgPct: 75,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Normal traffic flow.",
        hourlyPreview: [
          { time: "00:00", tempC: 23.5, rainRateMmH: 1.5, rainChancePct: 40, conditionCode: "partly_cloudy" },
          { time: "04:00", tempC: 23.2, rainRateMmH: 1.8, rainChancePct: 42, conditionCode: "partly_cloudy" },
          { time: "08:00", tempC: 26.8, rainRateMmH: 2.8, rainChancePct: 46, conditionCode: "drizzle" },
          { time: "12:00", tempC: 29.5, rainRateMmH: 3.8, rainChancePct: 50, conditionCode: "drizzle" },
          { time: "16:00", tempC: 28.0, rainRateMmH: 2.0, rainChancePct: 42, conditionCode: "partly_cloudy" },
          { time: "20:00", tempC: 25.5, rainRateMmH: 1.0, rainChancePct: 35, conditionCode: "partly_cloudy" },
        ],
      },
      {
        dayOffset: 6,
        ...getRelativeDate(6),
        condition: "Partly Cloudy",
        conditionCode: "partly_cloudy",
        tempMaxC: 30.8,
        tempMinC: 24.0,
        precipitationChancePct: 30,
        expectedRainfallMm: 8.0,
        windSpeedMaxKmh: 14,
        windDirection: "SE",
        humidityAvgPct: 70,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Nominal highway operations.",
        hourlyPreview: [
          { time: "00:00", tempC: 24.0, rainRateMmH: 0.5, rainChancePct: 25, conditionCode: "partly_cloudy" },
          { time: "04:00", tempC: 23.8, rainRateMmH: 0.8, rainChancePct: 28, conditionCode: "partly_cloudy" },
          { time: "08:00", tempC: 27.5, rainRateMmH: 1.5, rainChancePct: 32, conditionCode: "partly_cloudy" },
          { time: "12:00", tempC: 30.5, rainRateMmH: 2.2, rainChancePct: 35, conditionCode: "drizzle" },
          { time: "16:00", tempC: 29.0, rainRateMmH: 1.2, rainChancePct: 28, conditionCode: "partly_cloudy" },
          { time: "20:00", tempC: 26.0, rainRateMmH: 0.5, rainChancePct: 20, conditionCode: "clear" },
        ],
      },
      {
        dayOffset: 7,
        ...getRelativeDate(7),
        condition: "Clear and Pleasant",
        conditionCode: "clear",
        tempMaxC: 31.5,
        tempMinC: 24.2,
        precipitationChancePct: 20,
        expectedRainfallMm: 3.5,
        windSpeedMaxKmh: 12,
        windDirection: "E",
        humidityAvgPct: 66,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Good conditions for all road transport.",
        hourlyPreview: [
          { time: "00:00", tempC: 24.2, rainRateMmH: 0.2, rainChancePct: 15, conditionCode: "clear" },
          { time: "04:00", tempC: 24.0, rainRateMmH: 0.2, rainChancePct: 18, conditionCode: "clear" },
          { time: "08:00", tempC: 28.0, rainRateMmH: 0.5, rainChancePct: 20, conditionCode: "clear" },
          { time: "12:00", tempC: 31.2, rainRateMmH: 1.0, rainChancePct: 22, conditionCode: "partly_cloudy" },
          { time: "16:00", tempC: 29.8, rainRateMmH: 0.5, rainChancePct: 18, conditionCode: "clear" },
          { time: "20:00", tempC: 26.8, rainRateMmH: 0.2, rainChancePct: 15, conditionCode: "clear" },
        ],
      },
    ],
  },

  // 6. NAGALAND (Kohima)
  {
    id: "kohima-nh29",
    name: "Kohima & Chumukedima Mountain Pass",
    state: "Nagaland",
    district: "Kohima",
    corridor: "NH-29 (Dimapur-Kohima Lifeline)",
    highwayCode: "NH-29",
    elevationM: 1444,
    latitude: 25.6751,
    longitude: 94.1086,
    imdRadarStation: "IMD DWR Guwahati",
    live: {
      tempC: 20.8,
      feelsLikeC: 22.4,
      condition: "Dense Mountain Fog & Heavy Showers",
      conditionCode: "rain_heavy",
      tempMaxTodayC: 23.5,
      tempMinTodayC: 18.0,
      humidityPct: 95,
      windSpeedKmh: 19,
      windDirection: "SW",
      windGustKmh: 42,
      pressureHpa: 998.5,
      dewPointC: 20.0,
      uvIndex: 2,
      visibilityKm: 1.5,
      cloudCoverPct: 98,
      precipitationRateMmH: 13.5,
      rainAccumulated24hMm: 92.6,
      rainAccumulated72hMm: 204.0,
      aqi: 16,
      aqiLabel: "Good",
      soilMoistureVwc: 81.2,
      alertLevel: "ORANGE",
      alertHeadline: "Orange Alert: Chumukedima Mudslide & Sinking Zone Vulnerability",
      alertDescription: "Continuous saturation along Disang shale formations. Nagaland PWD and BRO clearing active slip.",
      dopplerRadarStatus: "Approaching Frontal Rain Band (42 dBZ)",
      dopplerEchoDbz: 42,
      stationStatus: "OPERATIONAL",
      timestamp: new Date().toISOString(),
    },
    forecast7Day: [
      {
        dayOffset: 1,
        ...getRelativeDate(1),
        condition: "Heavy Rain with Thunderstorms",
        conditionCode: "thunderstorm",
        tempMaxC: 22.5,
        tempMinC: 17.5,
        precipitationChancePct: 92,
        expectedRainfallMm: 78.0,
        windSpeedMaxKmh: 45,
        windDirection: "SW",
        humidityAvgPct: 95,
        landslideRiskTier: "CRITICAL",
        landslideRiskSummary: "Chumukedima 4-lane stretch vulnerable to toe sliding.",
        hourlyPreview: [
          { time: "00:00", tempC: 18.0, rainRateMmH: 9.0, rainChancePct: 88, conditionCode: "rain_heavy" },
          { time: "04:00", tempC: 17.5, rainRateMmH: 14.0, rainChancePct: 92, conditionCode: "thunderstorm" },
          { time: "08:00", tempC: 19.8, rainRateMmH: 18.5, rainChancePct: 95, conditionCode: "thunderstorm" },
          { time: "12:00", tempC: 22.2, rainRateMmH: 15.0, rainChancePct: 90, conditionCode: "rain_heavy" },
          { time: "16:00", tempC: 21.0, rainRateMmH: 9.5, rainChancePct: 85, conditionCode: "rain_moderate" },
          { time: "20:00", tempC: 19.0, rainRateMmH: 6.0, rainChancePct: 80, conditionCode: "rain_moderate" },
        ],
      },
      {
        dayOffset: 2,
        ...getRelativeDate(2),
        condition: "Moderate Rain Showers",
        conditionCode: "rain_moderate",
        tempMaxC: 23.0,
        tempMinC: 18.0,
        precipitationChancePct: 80,
        expectedRainfallMm: 50.0,
        windSpeedMaxKmh: 30,
        windDirection: "SSW",
        humidityAvgPct: 90,
        landslideRiskTier: "ELEVATED",
        landslideRiskSummary: "Controlled movement during daylight.",
        hourlyPreview: [
          { time: "00:00", tempC: 18.0, rainRateMmH: 6.0, rainChancePct: 75, conditionCode: "rain_moderate" },
          { time: "04:00", tempC: 17.8, rainRateMmH: 7.5, rainChancePct: 80, conditionCode: "rain_moderate" },
          { time: "08:00", tempC: 20.5, rainRateMmH: 10.0, rainChancePct: 84, conditionCode: "rain_moderate" },
          { time: "12:00", tempC: 22.8, rainRateMmH: 11.5, rainChancePct: 82, conditionCode: "rain_moderate" },
          { time: "16:00", tempC: 21.5, rainRateMmH: 7.0, rainChancePct: 75, conditionCode: "drizzle" },
          { time: "20:00", tempC: 19.5, rainRateMmH: 4.5, rainChancePct: 68, conditionCode: "drizzle" },
        ],
      },
      {
        dayOffset: 3,
        ...getRelativeDate(3),
        condition: "Passing Rain",
        conditionCode: "drizzle",
        tempMaxC: 24.0,
        tempMinC: 18.5,
        precipitationChancePct: 65,
        expectedRainfallMm: 32.0,
        windSpeedMaxKmh: 22,
        windDirection: "S",
        humidityAvgPct: 85,
        landslideRiskTier: "MODERATE",
        landslideRiskSummary: "Slump clearance ongoing; travel with caution.",
        hourlyPreview: [
          { time: "00:00", tempC: 18.5, rainRateMmH: 3.5, rainChancePct: 62, conditionCode: "drizzle" },
          { time: "04:00", tempC: 18.2, rainRateMmH: 4.0, rainChancePct: 65, conditionCode: "drizzle" },
          { time: "08:00", tempC: 21.0, rainRateMmH: 6.0, rainChancePct: 68, conditionCode: "drizzle" },
          { time: "12:00", tempC: 23.8, rainRateMmH: 7.0, rainChancePct: 70, conditionCode: "rain_moderate" },
          { time: "16:00", tempC: 22.2, rainRateMmH: 4.0, rainChancePct: 62, conditionCode: "drizzle" },
          { time: "20:00", tempC: 20.0, rainRateMmH: 2.8, rainChancePct: 55, conditionCode: "drizzle" },
        ],
      },
      {
        dayOffset: 4,
        ...getRelativeDate(4),
        condition: "Mist and Overcast",
        conditionCode: "overcast",
        tempMaxC: 24.8,
        tempMinC: 18.8,
        precipitationChancePct: 50,
        expectedRainfallMm: 20.0,
        windSpeedMaxKmh: 18,
        windDirection: "SE",
        humidityAvgPct: 80,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Stable slope conditions.",
        hourlyPreview: [
          { time: "00:00", tempC: 18.8, rainRateMmH: 2.0, rainChancePct: 45, conditionCode: "overcast" },
          { time: "04:00", tempC: 18.5, rainRateMmH: 2.2, rainChancePct: 48, conditionCode: "overcast" },
          { time: "08:00", tempC: 21.8, rainRateMmH: 3.5, rainChancePct: 52, conditionCode: "drizzle" },
          { time: "12:00", tempC: 24.5, rainRateMmH: 4.2, rainChancePct: 55, conditionCode: "drizzle" },
          { time: "16:00", tempC: 23.0, rainRateMmH: 2.5, rainChancePct: 45, conditionCode: "overcast" },
          { time: "20:00", tempC: 20.5, rainRateMmH: 1.8, rainChancePct: 38, conditionCode: "overcast" },
        ],
      },
      {
        dayOffset: 5,
        ...getRelativeDate(5),
        condition: "Partly Cloudy with Light Drizzle",
        conditionCode: "partly_cloudy",
        tempMaxC: 25.5,
        tempMinC: 19.0,
        precipitationChancePct: 40,
        expectedRainfallMm: 12.0,
        windSpeedMaxKmh: 15,
        windDirection: "SE",
        humidityAvgPct: 75,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Nominal operational state.",
        hourlyPreview: [
          { time: "00:00", tempC: 19.0, rainRateMmH: 1.0, rainChancePct: 35, conditionCode: "partly_cloudy" },
          { time: "04:00", tempC: 18.8, rainRateMmH: 1.2, rainChancePct: 38, conditionCode: "partly_cloudy" },
          { time: "08:00", tempC: 22.5, rainRateMmH: 2.2, rainChancePct: 42, conditionCode: "partly_cloudy" },
          { time: "12:00", tempC: 25.2, rainRateMmH: 3.0, rainChancePct: 45, conditionCode: "drizzle" },
          { time: "16:00", tempC: 23.8, rainRateMmH: 1.8, rainChancePct: 38, conditionCode: "partly_cloudy" },
          { time: "20:00", tempC: 21.0, rainRateMmH: 0.8, rainChancePct: 30, conditionCode: "partly_cloudy" },
        ],
      },
      {
        dayOffset: 6,
        ...getRelativeDate(6),
        condition: "Partly Cloudy",
        conditionCode: "partly_cloudy",
        tempMaxC: 26.2,
        tempMinC: 19.5,
        precipitationChancePct: 30,
        expectedRainfallMm: 6.5,
        windSpeedMaxKmh: 12,
        windDirection: "E",
        humidityAvgPct: 70,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Clear road transit.",
        hourlyPreview: [
          { time: "00:00", tempC: 19.5, rainRateMmH: 0.5, rainChancePct: 25, conditionCode: "partly_cloudy" },
          { time: "04:00", tempC: 19.2, rainRateMmH: 0.5, rainChancePct: 28, conditionCode: "partly_cloudy" },
          { time: "08:00", tempC: 23.2, rainRateMmH: 1.2, rainChancePct: 32, conditionCode: "partly_cloudy" },
          { time: "12:00", tempC: 26.0, rainRateMmH: 1.8, rainChancePct: 35, conditionCode: "drizzle" },
          { time: "16:00", tempC: 24.5, rainRateMmH: 1.0, rainChancePct: 28, conditionCode: "partly_cloudy" },
          { time: "20:00", tempC: 21.8, rainRateMmH: 0.5, rainChancePct: 20, conditionCode: "clear" },
        ],
      },
      {
        dayOffset: 7,
        ...getRelativeDate(7),
        condition: "Sunny and Clear",
        conditionCode: "clear",
        tempMaxC: 27.0,
        tempMinC: 20.0,
        precipitationChancePct: 15,
        expectedRainfallMm: 2.5,
        windSpeedMaxKmh: 10,
        windDirection: "E",
        humidityAvgPct: 65,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Green conditions. Highway operations fully restored.",
        hourlyPreview: [
          { time: "00:00", tempC: 20.0, rainRateMmH: 0.0, rainChancePct: 10, conditionCode: "clear" },
          { time: "04:00", tempC: 19.8, rainRateMmH: 0.2, rainChancePct: 12, conditionCode: "clear" },
          { time: "08:00", tempC: 23.8, rainRateMmH: 0.5, rainChancePct: 15, conditionCode: "clear" },
          { time: "12:00", tempC: 26.8, rainRateMmH: 0.8, rainChancePct: 18, conditionCode: "partly_cloudy" },
          { time: "16:00", tempC: 25.2, rainRateMmH: 0.2, rainChancePct: 12, conditionCode: "clear" },
          { time: "20:00", tempC: 22.5, rainRateMmH: 0.0, rainChancePct: 10, conditionCode: "clear" },
        ],
      },
    ],
  },

  // 7. MANIPUR (Noney & Tupul Chute)
  {
    id: "noney-nh37",
    name: "Noney & Tupul Chute Chasm",
    state: "Manipur",
    district: "Noney",
    corridor: "NH-37 (Imphal-Jiribam Lifeline)",
    highwayCode: "NH-37",
    elevationM: 810,
    latitude: 24.8167,
    longitude: 93.6333,
    imdRadarStation: "IMD DWR Silchar",
    live: {
      tempC: 26.4,
      feelsLikeC: 29.8,
      condition: "Tropical Downpour & Debris Flow Watch",
      conditionCode: "rain_heavy",
      tempMaxTodayC: 29.0,
      tempMinTodayC: 23.0,
      humidityPct: 93,
      windSpeedKmh: 20,
      windDirection: "SSW",
      windGustKmh: 46,
      pressureHpa: 1002.4,
      dewPointC: 24.8,
      uvIndex: 3,
      visibilityKm: 2.8,
      cloudCoverPct: 98,
      precipitationRateMmH: 19.8,
      rainAccumulated24hMm: 128.5,
      rainAccumulated72hMm: 280.0,
      aqi: 20,
      aqiLabel: "Good",
      soilMoistureVwc: 86.4,
      alertLevel: "RED",
      alertHeadline: "Red Alert: Tupul Railway Construction Chute Debris Flow Threat",
      alertDescription:
        "Severe rainfall triggering mass movements along Ijei river valley. Extreme caution for NH-37 bridges and railway construction camps.",
      dopplerRadarStatus: "Intense Convective Squall (49 dBZ)",
      dopplerEchoDbz: 49,
      stationStatus: "OPERATIONAL",
      timestamp: new Date().toISOString(),
    },
    forecast7Day: [
      {
        dayOffset: 1,
        ...getRelativeDate(1),
        condition: "Severe Torrential Storm",
        conditionCode: "thunderstorm",
        tempMaxC: 28.0,
        tempMinC: 22.5,
        precipitationChancePct: 96,
        expectedRainfallMm: 104.0,
        windSpeedMaxKmh: 50,
        windDirection: "SW",
        humidityAvgPct: 97,
        landslideRiskTier: "CRITICAL",
        landslideRiskSummary: "Critical debris flow threat in Tupul basin. Evacuate low-lying construction camps.",
        hourlyPreview: [
          { time: "00:00", tempC: 23.0, rainRateMmH: 15.0, rainChancePct: 92, conditionCode: "rain_heavy" },
          { time: "04:00", tempC: 22.5, rainRateMmH: 20.0, rainChancePct: 96, conditionCode: "thunderstorm" },
          { time: "08:00", tempC: 25.0, rainRateMmH: 26.0, rainChancePct: 98, conditionCode: "thunderstorm" },
          { time: "12:00", tempC: 27.5, rainRateMmH: 20.0, rainChancePct: 94, conditionCode: "rain_heavy" },
          { time: "16:00", tempC: 26.2, rainRateMmH: 12.0, rainChancePct: 88, conditionCode: "rain_moderate" },
          { time: "20:00", tempC: 24.5, rainRateMmH: 7.5, rainChancePct: 82, conditionCode: "rain_moderate" },
        ],
      },
      {
        dayOffset: 2,
        ...getRelativeDate(2),
        condition: "Heavy Rain with Thunder",
        conditionCode: "rain_heavy",
        tempMaxC: 28.5,
        tempMinC: 23.0,
        precipitationChancePct: 88,
        expectedRainfallMm: 72.0,
        windSpeedMaxKmh: 36,
        windDirection: "SW",
        humidityAvgPct: 92,
        landslideRiskTier: "CRITICAL",
        landslideRiskSummary: "Continued riverbed siltation and embankment scouring.",
        hourlyPreview: [
          { time: "00:00", tempC: 23.2, rainRateMmH: 9.0, rainChancePct: 84, conditionCode: "rain_moderate" },
          { time: "04:00", tempC: 22.8, rainRateMmH: 12.0, rainChancePct: 88, conditionCode: "rain_heavy" },
          { time: "08:00", tempC: 25.5, rainRateMmH: 16.0, rainChancePct: 90, conditionCode: "rain_heavy" },
          { time: "12:00", tempC: 28.0, rainRateMmH: 17.5, rainChancePct: 88, conditionCode: "rain_heavy" },
          { time: "16:00", tempC: 26.8, rainRateMmH: 10.0, rainChancePct: 80, conditionCode: "rain_moderate" },
          { time: "20:00", tempC: 25.0, rainRateMmH: 6.0, rainChancePct: 74, conditionCode: "rain_moderate" },
        ],
      },
      {
        dayOffset: 3,
        ...getRelativeDate(3),
        condition: "Moderate Rain Showers",
        conditionCode: "rain_moderate",
        tempMaxC: 29.5,
        tempMinC: 23.5,
        precipitationChancePct: 78,
        expectedRainfallMm: 46.0,
        windSpeedMaxKmh: 28,
        windDirection: "SSW",
        humidityAvgPct: 86,
        landslideRiskTier: "ELEVATED",
        landslideRiskSummary: "Highway passable with designated escorts.",
        hourlyPreview: [
          { time: "00:00", tempC: 23.5, rainRateMmH: 6.0, rainChancePct: 72, conditionCode: "rain_moderate" },
          { time: "04:00", tempC: 23.2, rainRateMmH: 7.5, rainChancePct: 76, conditionCode: "rain_moderate" },
          { time: "08:00", tempC: 26.2, rainRateMmH: 10.5, rainChancePct: 80, conditionCode: "rain_moderate" },
          { time: "12:00", tempC: 29.0, rainRateMmH: 12.0, rainChancePct: 82, conditionCode: "rain_moderate" },
          { time: "16:00", tempC: 27.5, rainRateMmH: 7.0, rainChancePct: 74, conditionCode: "drizzle" },
          { time: "20:00", tempC: 25.5, rainRateMmH: 4.5, rainChancePct: 66, conditionCode: "drizzle" },
        ],
      },
      {
        dayOffset: 4,
        ...getRelativeDate(4),
        condition: "Drizzle and Overcast",
        conditionCode: "drizzle",
        tempMaxC: 30.0,
        tempMinC: 24.0,
        precipitationChancePct: 62,
        expectedRainfallMm: 28.0,
        windSpeedMaxKmh: 22,
        windDirection: "S",
        humidityAvgPct: 80,
        landslideRiskTier: "MODERATE",
        landslideRiskSummary: "Restoration of road edges underway.",
        hourlyPreview: [
          { time: "00:00", tempC: 24.0, rainRateMmH: 3.5, rainChancePct: 58, conditionCode: "drizzle" },
          { time: "04:00", tempC: 23.8, rainRateMmH: 4.0, rainChancePct: 60, conditionCode: "drizzle" },
          { time: "08:00", tempC: 27.0, rainRateMmH: 5.5, rainChancePct: 65, conditionCode: "drizzle" },
          { time: "12:00", tempC: 29.5, rainRateMmH: 6.5, rainChancePct: 66, conditionCode: "rain_moderate" },
          { time: "16:00", tempC: 28.0, rainRateMmH: 4.2, rainChancePct: 60, conditionCode: "drizzle" },
          { time: "20:00", tempC: 26.0, rainRateMmH: 3.0, rainChancePct: 52, conditionCode: "drizzle" },
        ],
      },
      {
        dayOffset: 5,
        ...getRelativeDate(5),
        condition: "Passing Rain Showers",
        conditionCode: "drizzle",
        tempMaxC: 30.8,
        tempMinC: 24.2,
        precipitationChancePct: 48,
        expectedRainfallMm: 16.0,
        windSpeedMaxKmh: 18,
        windDirection: "SE",
        humidityAvgPct: 76,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Nominal operational state.",
        hourlyPreview: [
          { time: "00:00", tempC: 24.2, rainRateMmH: 1.8, rainChancePct: 42, conditionCode: "drizzle" },
          { time: "04:00", tempC: 24.0, rainRateMmH: 2.0, rainChancePct: 45, conditionCode: "drizzle" },
          { time: "08:00", tempC: 27.5, rainRateMmH: 3.2, rainChancePct: 50, conditionCode: "drizzle" },
          { time: "12:00", tempC: 30.2, rainRateMmH: 4.0, rainChancePct: 52, conditionCode: "drizzle" },
          { time: "16:00", tempC: 28.8, rainRateMmH: 2.5, rainChancePct: 45, conditionCode: "drizzle" },
          { time: "20:00", tempC: 26.5, rainRateMmH: 1.5, rainChancePct: 38, conditionCode: "overcast" },
        ],
      },
      {
        dayOffset: 6,
        ...getRelativeDate(6),
        condition: "Partly Cloudy",
        conditionCode: "partly_cloudy",
        tempMaxC: 31.5,
        tempMinC: 24.8,
        precipitationChancePct: 35,
        expectedRainfallMm: 9.0,
        windSpeedMaxKmh: 14,
        windDirection: "E",
        humidityAvgPct: 70,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Clear road conditions.",
        hourlyPreview: [
          { time: "00:00", tempC: 24.8, rainRateMmH: 0.8, rainChancePct: 30, conditionCode: "partly_cloudy" },
          { time: "04:00", tempC: 24.5, rainRateMmH: 1.0, rainChancePct: 32, conditionCode: "partly_cloudy" },
          { time: "08:00", tempC: 28.2, rainRateMmH: 1.8, rainChancePct: 36, conditionCode: "partly_cloudy" },
          { time: "12:00", tempC: 31.0, rainRateMmH: 2.5, rainChancePct: 38, conditionCode: "drizzle" },
          { time: "16:00", tempC: 29.5, rainRateMmH: 1.5, rainChancePct: 32, conditionCode: "partly_cloudy" },
          { time: "20:00", tempC: 27.0, rainRateMmH: 0.8, rainChancePct: 24, conditionCode: "clear" },
        ],
      },
      {
        dayOffset: 7,
        ...getRelativeDate(7),
        condition: "Clear and Warm",
        conditionCode: "clear",
        tempMaxC: 32.2,
        tempMinC: 25.0,
        precipitationChancePct: 20,
        expectedRainfallMm: 4.0,
        windSpeedMaxKmh: 12,
        windDirection: "E",
        humidityAvgPct: 65,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Optimal weather for logistics and transport.",
        hourlyPreview: [
          { time: "00:00", tempC: 25.0, rainRateMmH: 0.2, rainChancePct: 15, conditionCode: "clear" },
          { time: "04:00", tempC: 24.8, rainRateMmH: 0.2, rainChancePct: 18, conditionCode: "clear" },
          { time: "08:00", tempC: 28.8, rainRateMmH: 0.5, rainChancePct: 20, conditionCode: "clear" },
          { time: "12:00", tempC: 31.8, rainRateMmH: 1.0, rainChancePct: 22, conditionCode: "partly_cloudy" },
          { time: "16:00", tempC: 30.2, rainRateMmH: 0.5, rainChancePct: 18, conditionCode: "clear" },
          { time: "20:00", tempC: 27.5, rainRateMmH: 0.2, rainChancePct: 15, conditionCode: "clear" },
        ],
      },
    ],
  },

  // 8. TRIPURA (Baramura & Dhalai)
  {
    id: "baramura-nh8",
    name: "Baramura Range & Atharamura Pass",
    state: "Tripura",
    district: "West Tripura / Dhalai",
    corridor: "NH-8 (Tripura Lifeline Corridor)",
    highwayCode: "NH-8",
    elevationM: 320,
    latitude: 23.8315,
    longitude: 91.5647,
    imdRadarStation: "IMD DWR Agartala (MBB Airport)",
    live: {
      tempC: 29.2,
      feelsLikeC: 34.5,
      condition: "Tropical Heat & Scattered Thunderstorms",
      conditionCode: "thunderstorm",
      tempMaxTodayC: 32.0,
      tempMinTodayC: 26.0,
      humidityPct: 88,
      windSpeedKmh: 17,
      windDirection: "SSE",
      windGustKmh: 35,
      pressureHpa: 1007.0,
      dewPointC: 26.5,
      uvIndex: 5,
      visibilityKm: 5.0,
      cloudCoverPct: 85,
      precipitationRateMmH: 12.0,
      rainAccumulated24hMm: 62.0,
      rainAccumulated72hMm: 139.0,
      aqi: 26,
      aqiLabel: "Good",
      soilMoistureVwc: 72.8,
      alertLevel: "YELLOW",
      alertHeadline: "Yellow Alert: Monsoon Rain Spells on Baramura Road Cuts",
      alertDescription: "Moderate slope toe erosion in Atharamura and Longthorai hill ranges. NH-8 operational with periodic sweeps.",
      dopplerRadarStatus: "Isolated Convective Cells (38 dBZ)",
      dopplerEchoDbz: 38,
      stationStatus: "OPERATIONAL",
      timestamp: new Date().toISOString(),
    },
    forecast7Day: [
      {
        dayOffset: 1,
        ...getRelativeDate(1),
        condition: "Thunderstorm with High Humidity",
        conditionCode: "thunderstorm",
        tempMaxC: 30.5,
        tempMinC: 25.5,
        precipitationChancePct: 85,
        expectedRainfallMm: 65.0,
        windSpeedMaxKmh: 38,
        windDirection: "S",
        humidityAvgPct: 90,
        landslideRiskTier: "ELEVATED",
        landslideRiskSummary: "Watch for shallow debris slumps along Tipam sandstone cut slopes.",
        hourlyPreview: [
          { time: "00:00", tempC: 26.0, rainRateMmH: 6.0, rainChancePct: 75, conditionCode: "rain_moderate" },
          { time: "04:00", tempC: 25.5, rainRateMmH: 8.5, rainChancePct: 80, conditionCode: "rain_moderate" },
          { time: "08:00", tempC: 28.0, rainRateMmH: 15.0, rainChancePct: 88, conditionCode: "thunderstorm" },
          { time: "12:00", tempC: 30.2, rainRateMmH: 16.0, rainChancePct: 85, conditionCode: "thunderstorm" },
          { time: "16:00", tempC: 29.0, rainRateMmH: 9.0, rainChancePct: 78, conditionCode: "rain_moderate" },
          { time: "20:00", tempC: 27.2, rainRateMmH: 5.0, rainChancePct: 70, conditionCode: "drizzle" },
        ],
      },
      {
        dayOffset: 2,
        ...getRelativeDate(2),
        condition: "Moderate Rain Showers",
        conditionCode: "rain_moderate",
        tempMaxC: 31.0,
        tempMinC: 26.0,
        precipitationChancePct: 75,
        expectedRainfallMm: 48.0,
        windSpeedMaxKmh: 28,
        windDirection: "SSW",
        humidityAvgPct: 85,
        landslideRiskTier: "MODERATE",
        landslideRiskSummary: "Highway traffic nominal.",
        hourlyPreview: [
          { time: "00:00", tempC: 26.0, rainRateMmH: 4.5, rainChancePct: 68, conditionCode: "drizzle" },
          { time: "04:00", tempC: 25.8, rainRateMmH: 5.5, rainChancePct: 72, conditionCode: "drizzle" },
          { time: "08:00", tempC: 28.5, rainRateMmH: 9.0, rainChancePct: 78, conditionCode: "rain_moderate" },
          { time: "12:00", tempC: 30.8, rainRateMmH: 10.5, rainChancePct: 78, conditionCode: "rain_moderate" },
          { time: "16:00", tempC: 29.5, rainRateMmH: 6.0, rainChancePct: 70, conditionCode: "drizzle" },
          { time: "20:00", tempC: 27.5, rainRateMmH: 3.5, rainChancePct: 62, conditionCode: "drizzle" },
        ],
      },
      {
        dayOffset: 3,
        ...getRelativeDate(3),
        condition: "Passing Rain",
        conditionCode: "drizzle",
        tempMaxC: 32.0,
        tempMinC: 26.2,
        precipitationChancePct: 60,
        expectedRainfallMm: 28.0,
        windSpeedMaxKmh: 22,
        windDirection: "S",
        humidityAvgPct: 80,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Stable slope conditions.",
        hourlyPreview: [
          { time: "00:00", tempC: 26.2, rainRateMmH: 2.5, rainChancePct: 55, conditionCode: "drizzle" },
          { time: "04:00", tempC: 26.0, rainRateMmH: 3.0, rainChancePct: 58, conditionCode: "drizzle" },
          { time: "08:00", tempC: 29.0, rainRateMmH: 5.0, rainChancePct: 62, conditionCode: "drizzle" },
          { time: "12:00", tempC: 31.8, rainRateMmH: 6.0, rainChancePct: 65, conditionCode: "rain_moderate" },
          { time: "16:00", tempC: 30.2, rainRateMmH: 3.8, rainChancePct: 58, conditionCode: "drizzle" },
          { time: "20:00", tempC: 28.0, rainRateMmH: 2.2, rainChancePct: 50, conditionCode: "overcast" },
        ],
      },
      {
        dayOffset: 4,
        ...getRelativeDate(4),
        condition: "Partly Cloudy",
        conditionCode: "partly_cloudy",
        tempMaxC: 32.8,
        tempMinC: 26.5,
        precipitationChancePct: 45,
        expectedRainfallMm: 16.0,
        windSpeedMaxKmh: 18,
        windDirection: "SE",
        humidityAvgPct: 75,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Nominal highway operations.",
        hourlyPreview: [
          { time: "00:00", tempC: 26.5, rainRateMmH: 1.2, rainChancePct: 40, conditionCode: "partly_cloudy" },
          { time: "04:00", tempC: 26.2, rainRateMmH: 1.5, rainChancePct: 42, conditionCode: "partly_cloudy" },
          { time: "08:00", tempC: 29.5, rainRateMmH: 2.8, rainChancePct: 48, conditionCode: "drizzle" },
          { time: "12:00", tempC: 32.5, rainRateMmH: 3.5, rainChancePct: 50, conditionCode: "drizzle" },
          { time: "16:00", tempC: 31.0, rainRateMmH: 2.0, rainChancePct: 42, conditionCode: "partly_cloudy" },
          { time: "20:00", tempC: 28.5, rainRateMmH: 1.0, rainChancePct: 35, conditionCode: "partly_cloudy" },
        ],
      },
      {
        dayOffset: 5,
        ...getRelativeDate(5),
        condition: "Partly Cloudy with Sunshine",
        conditionCode: "partly_cloudy",
        tempMaxC: 33.5,
        tempMinC: 27.0,
        precipitationChancePct: 35,
        expectedRainfallMm: 10.0,
        windSpeedMaxKmh: 15,
        windDirection: "E",
        humidityAvgPct: 70,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Highway fully clear.",
        hourlyPreview: [
          { time: "00:00", tempC: 27.0, rainRateMmH: 0.8, rainChancePct: 30, conditionCode: "partly_cloudy" },
          { time: "04:00", tempC: 26.8, rainRateMmH: 1.0, rainChancePct: 32, conditionCode: "partly_cloudy" },
          { time: "08:00", tempC: 30.2, rainRateMmH: 1.8, rainChancePct: 38, conditionCode: "partly_cloudy" },
          { time: "12:00", tempC: 33.2, rainRateMmH: 2.5, rainChancePct: 40, conditionCode: "drizzle" },
          { time: "16:00", tempC: 31.8, rainRateMmH: 1.5, rainChancePct: 34, conditionCode: "partly_cloudy" },
          { time: "20:00", tempC: 29.0, rainRateMmH: 0.8, rainChancePct: 25, conditionCode: "clear" },
        ],
      },
      {
        dayOffset: 6,
        ...getRelativeDate(6),
        condition: "Sunny and Warm",
        conditionCode: "clear",
        tempMaxC: 34.0,
        tempMinC: 27.2,
        precipitationChancePct: 20,
        expectedRainfallMm: 5.0,
        windSpeedMaxKmh: 12,
        windDirection: "E",
        humidityAvgPct: 65,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Safe driving conditions.",
        hourlyPreview: [
          { time: "00:00", tempC: 27.2, rainRateMmH: 0.2, rainChancePct: 18, conditionCode: "clear" },
          { time: "04:00", tempC: 27.0, rainRateMmH: 0.2, rainChancePct: 20, conditionCode: "clear" },
          { time: "08:00", tempC: 30.8, rainRateMmH: 0.8, rainChancePct: 22, conditionCode: "clear" },
          { time: "12:00", tempC: 33.8, rainRateMmH: 1.2, rainChancePct: 25, conditionCode: "partly_cloudy" },
          { time: "16:00", tempC: 32.2, rainRateMmH: 0.5, rainChancePct: 20, conditionCode: "clear" },
          { time: "20:00", tempC: 29.5, rainRateMmH: 0.2, rainChancePct: 15, conditionCode: "clear" },
        ],
      },
      {
        dayOffset: 7,
        ...getRelativeDate(7),
        condition: "Clear and Sunny",
        conditionCode: "clear",
        tempMaxC: 34.5,
        tempMinC: 27.5,
        precipitationChancePct: 15,
        expectedRainfallMm: 2.0,
        windSpeedMaxKmh: 10,
        windDirection: "ENE",
        humidityAvgPct: 62,
        landslideRiskTier: "LOW",
        landslideRiskSummary: "Baseline conditions across all routes.",
        hourlyPreview: [
          { time: "00:00", tempC: 27.5, rainRateMmH: 0.0, rainChancePct: 10, conditionCode: "clear" },
          { time: "04:00", tempC: 27.2, rainRateMmH: 0.0, rainChancePct: 12, conditionCode: "clear" },
          { time: "08:00", tempC: 31.2, rainRateMmH: 0.5, rainChancePct: 15, conditionCode: "clear" },
          { time: "12:00", tempC: 34.2, rainRateMmH: 0.8, rainChancePct: 18, conditionCode: "clear" },
          { time: "16:00", tempC: 32.8, rainRateMmH: 0.2, rainChancePct: 12, conditionCode: "clear" },
          { time: "20:00", tempC: 30.0, rainRateMmH: 0.0, rainChancePct: 10, conditionCode: "clear" },
        ],
      },
    ],
  },
];
